/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Comercial.dominio;

//import Comercial.dominio.ListadoProveedores;
import Comercial.datos.Conexion;
import Comercial.dominio.FormaPago;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import Comercial.datos.Conexion;
import Comercial.datos.FormaPagoDAO;
import java.text.SimpleDateFormat;

/**
 *
 * @author SipaqueRitaMaria
 */
public class Mantenimiento_FormaPago extends javax.swing.JInternalFrame {

    /**
     * Creates new form Mantenimiento_FormaPago
     */
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("CodigoProveedor");
        modelo.addColumn("Transaccion");
        modelo.addColumn("Forma");
        modelo.addColumn("Dias");
        modelo.addColumn("Fecha");
        modelo.addColumn("Estatus");
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();

        List<FormaPago> proveedor = proveedorDAO.select();
        tbpago.setModel(modelo);
        String[] dato = new String[7];
        for (int i = 0; i < proveedor.size(); i++) {
            dato[0] = Integer.toString(proveedor.get(i).getPK_codigo_pago());
            dato[1] = proveedor.get(i).getCodigo_proveedor();
            dato[2] = proveedor.get(i).getTipo_pago();
            dato[3] = proveedor.get(i).getForma_pago();
            dato[4] = proveedor.get(i).getDias_pago();
            dato[5] = proveedor.get(i).getFecha_pago();
            dato[6] = proveedor.get(i).getEstatus_pago();

            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscar() {
        FormaPago proveedorAConsultar = new FormaPago();
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();
        proveedorAConsultar.setPK_codigo_pago(Integer.parseInt(Txt_ID.getText()));
        proveedorAConsultar = proveedorDAO.query(proveedorAConsultar);
        Txt_codigoproveedor.setText(proveedorAConsultar.getCodigo_proveedor());
        txt_tipopago.setSelectedItem(proveedorAConsultar.getTipo_pago());
        txt_formapago.setSelectedItem(proveedorAConsultar.getForma_pago());
        txt_dias.setSelectedItem(proveedorAConsultar.getDias_pago());
        Txt_Fecha.setText(proveedorAConsultar.getFecha_pago());

        Txt_estatus.setText(proveedorAConsultar.getEstatus_pago());

    }

    public void limpiar() {
        Txt_ID.setText("");
        Txt_codigoproveedor.setText("");
        txt_tipopago.setSelectedItem(null);
        txt_formapago.setSelectedItem(null);
         txt_dias.setSelectedItem(null);
                
        Txt_Fecha.setText("");
        Txt_estatus.setText("");


    }

    public Mantenimiento_FormaPago() {
        initComponents();
        llenadoDeTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LbTITULO = new javax.swing.JLabel();
        Pnl_datos2 = new javax.swing.JPanel();
        Lbl_codigo2 = new javax.swing.JLabel();
        Txt_ID = new javax.swing.JTextField();
        Lbl_nombre2 = new javax.swing.JLabel();
        Lbl_direccion2 = new javax.swing.JLabel();
        Lbl_telefono2 = new javax.swing.JLabel();
        Lbl_nit2 = new javax.swing.JLabel();
        Txt_estatus = new javax.swing.JTextField();
        Btn_Reporte4 = new javax.swing.JButton();
        Btn_Guardar2 = new javax.swing.JButton();
        Btn_Modificar2 = new javax.swing.JButton();
        Btn_Eliminar2 = new javax.swing.JButton();
        Btn_Reporte5 = new javax.swing.JButton();
        Txt_Fecha = new javax.swing.JTextField();
        txt_dias = new javax.swing.JComboBox<>();
        Lbl_direccion3 = new javax.swing.JLabel();
        txt_formapago = new javax.swing.JComboBox<>();
        Lbl_nombre4 = new javax.swing.JLabel();
        txt_tipopago = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        Txt_codigoproveedor = new javax.swing.JTextField();
        Pnl_datos3 = new javax.swing.JPanel();
        Lbl_nombre3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpago = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setVisible(true);

        LbTITULO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LbTITULO.setText("Mantenimiento Forma Pago");

        Pnl_datos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Forma Pago"));

        Lbl_codigo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_codigo2.setText("Codigo Forma Pago:");

        Lbl_nombre2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre2.setText("Codigo Proveeedor:");

        Lbl_direccion2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion2.setText("Dias pago:");

        Lbl_telefono2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_telefono2.setText("Fecha Pago:");

        Lbl_nit2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nit2.setText("Estatus Forma Pago:");

        Btn_Reporte4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte4.setText("Reporte");
        Btn_Reporte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte4ActionPerformed(evt);
            }
        });

        Btn_Guardar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Guardar2.setText("Guardar");
        Btn_Guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Guardar2ActionPerformed(evt);
            }
        });

        Btn_Modificar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Modificar2.setText("Modificar");
        Btn_Modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Modificar2ActionPerformed(evt);
            }
        });

        Btn_Eliminar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Eliminar2.setText("Eliminar");
        Btn_Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Eliminar2ActionPerformed(evt);
            }
        });

        Btn_Reporte5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte5.setText("Buscar");
        Btn_Reporte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte5ActionPerformed(evt);
            }
        });

        txt_dias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 dias", "15 dias", "30 dias", "60 dias", " " }));

        Lbl_direccion3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion3.setText("Forma de pago:");

        txt_formapago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));

        Lbl_nombre4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre4.setText("Tipo de Pago:");

        txt_tipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura Compra", "Orden de Compra", "Resepcion de Compra", "Devolucion de Compra", " " }));

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Txt_codigoproveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Txt_codigoproveedor.setBorder(null);
        Txt_codigoproveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txt_codigoproveedorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Txt_codigoproveedorKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout Pnl_datos2Layout = new javax.swing.GroupLayout(Pnl_datos2);
        Pnl_datos2.setLayout(Pnl_datos2Layout);
        Pnl_datos2Layout.setHorizontalGroup(
            Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_nombre2)
                    .addComponent(Lbl_codigo2))
                .addGap(44, 44, 44)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_ID, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(Txt_codigoproveedor))
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Btn_Reporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addComponent(Btn_Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Btn_Reporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_datos2Layout.createSequentialGroup()
                                    .addComponent(Lbl_nit2)
                                    .addGap(18, 18, 18)
                                    .addComponent(Txt_estatus))
                                .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                    .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lbl_telefono2)
                                        .addComponent(Lbl_direccion2))
                                    .addGap(302, 302, 302)))))
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_nombre4)
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Lbl_direccion3)))
                        .addGap(60, 60, 60)
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        Pnl_datos2Layout.setVerticalGroup(
            Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_codigo2)
                    .addComponent(Txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre2)
                    .addComponent(jButton1)
                    .addComponent(Txt_codigoproveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre4)
                    .addComponent(txt_tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_direccion3))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_direccion2)
                    .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Lbl_telefono2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datos2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nit2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        Pnl_datos3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Forma Pago"));

        Lbl_nombre3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N

        tbpago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbpago.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbpagoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tbpagoAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbpago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpagoMouseClicked(evt);
            }
        });
        tbpago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbpagoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbpago);

        javax.swing.GroupLayout Pnl_datos3Layout = new javax.swing.GroupLayout(Pnl_datos3);
        Pnl_datos3.setLayout(Pnl_datos3Layout);
        Pnl_datos3Layout.setHorizontalGroup(
            Pnl_datos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos3Layout.createSequentialGroup()
                .addGroup(Pnl_datos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos3Layout.createSequentialGroup()
                        .addComponent(Lbl_nombre3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pnl_datos3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)))
                .addContainerGap())
        );
        Pnl_datos3Layout.setVerticalGroup(
            Pnl_datos3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datos3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_nombre3)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LbTITULO)
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pnl_datos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pnl_datos3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LbTITULO)
                .addGap(18, 18, 18)
                .addComponent(Pnl_datos2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pnl_datos3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Reporte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte4ActionPerformed

    }//GEN-LAST:event_Btn_Reporte4ActionPerformed

    private void Btn_Guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Guardar2ActionPerformed
        // TODO add your handling code here:

        FormaPagoDAO emisionchequeDAO = new FormaPagoDAO();
        FormaPago insertar = new FormaPago();

        insertar.setPK_codigo_pago((int) Integer.parseInt(Txt_ID.getText()));
        insertar.setCodigo_proveedor(Txt_codigoproveedor.getText());
        insertar.setTipo_pago(txt_tipopago.getSelectedItem().toString());
        insertar.setForma_pago(txt_formapago.getSelectedItem().toString());
        insertar.setDias_pago(txt_dias.getSelectedItem().toString());
       
        insertar.setFecha_pago(Txt_Fecha.getText());

        insertar.setEstatus_pago(Txt_estatus.getText());
 
        emisionchequeDAO.insert(insertar);

        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_Guardar2ActionPerformed

    private void Btn_Modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Modificar2ActionPerformed
        // TODO add your handling code here:
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();
        FormaPago proveedorAActualizar = new FormaPago();
        proveedorAActualizar.setPK_codigo_pago(Integer.parseInt(Txt_ID.getText()));
        proveedorAActualizar.setCodigo_proveedor(Txt_codigoproveedor.getText());
        proveedorAActualizar.setTipo_pago(txt_tipopago.getSelectedItem().toString());
        proveedorAActualizar.setForma_pago(txt_formapago.getSelectedItem().toString());
        proveedorAActualizar.setDias_pago(txt_dias.getSelectedItem().toString());
       proveedorAActualizar.setFecha_pago(Txt_Fecha.getText());
        proveedorAActualizar.setEstatus_pago(Txt_estatus.getText());

        proveedorDAO.update(proveedorAActualizar);
        JOptionPane.showMessageDialog(null, "Modificación Exitosa.");
        limpiar();
        llenadoDeTablas();
    }//GEN-LAST:event_Btn_Modificar2ActionPerformed

    private void Btn_Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Eliminar2ActionPerformed
        // TODO add your handling code here:
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();
        FormaPago proveedorAEliminar = new FormaPago();
        proveedorAEliminar.setPK_codigo_pago(Integer.parseInt(Txt_ID.getText()));
        proveedorDAO.delete(proveedorAEliminar);
        JOptionPane.showMessageDialog(null, "Registro Eliminado.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_Eliminar2ActionPerformed

    private void Btn_Reporte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte5ActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_Btn_Reporte5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        ListadoProveedores abrir = new ListadoProveedores();
//        abrir.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_codigoproveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_codigoproveedorKeyPressed

    }//GEN-LAST:event_Txt_codigoproveedorKeyPressed

    private void Txt_codigoproveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txt_codigoproveedorKeyTyped

    }//GEN-LAST:event_Txt_codigoproveedorKeyTyped

    private void tbpagoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbpagoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoAncestorAdded

    private void tbpagoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbpagoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoAncestorMoved

    private void tbpagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpagoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoMouseClicked

    private void tbpagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbpagoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Eliminar2;
    public javax.swing.JButton Btn_Guardar2;
    public javax.swing.JButton Btn_Modificar2;
    public javax.swing.JButton Btn_Reporte4;
    public javax.swing.JButton Btn_Reporte5;
    private javax.swing.JLabel LbTITULO;
    private javax.swing.JLabel Lbl_codigo2;
    private javax.swing.JLabel Lbl_direccion2;
    private javax.swing.JLabel Lbl_direccion3;
    private javax.swing.JLabel Lbl_nit2;
    private javax.swing.JLabel Lbl_nombre2;
    private javax.swing.JLabel Lbl_nombre3;
    private javax.swing.JLabel Lbl_nombre4;
    private javax.swing.JLabel Lbl_telefono2;
    private javax.swing.JPanel Pnl_datos2;
    private javax.swing.JPanel Pnl_datos3;
    public javax.swing.JTextField Txt_Fecha;
    public javax.swing.JTextField Txt_ID;
    public static javax.swing.JTextField Txt_codigoproveedor;
    public javax.swing.JTextField Txt_estatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbpago;
    private javax.swing.JComboBox<String> txt_dias;
    private javax.swing.JComboBox<String> txt_formapago;
    private javax.swing.JComboBox<String> txt_tipopago;
    // End of variables declaration//GEN-END:variables
}
