/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Comercial.vista;

import Comercial.datos.AutorizacionOrdenCompraDAO;
import Comercial.dominio.AutorizacionOrdenCompra1;
import java.awt.Color;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Comercial.datos.Conexion;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author SipaqueRitaMaria
 */
public class AutorizacionOrdenCompra extends javax.swing.JInternalFrame {
AutorizacionOrdenCompraDAO cargarCombobox = new AutorizacionOrdenCompraDAO();
int estadovalidacion;
    /**
     * Creates new form AutorizacionOrdenCompra
     */

 public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("CodigoOrdenCompra");
        modelo.addColumn("Autorizante");
        modelo.addColumn("Puesto");
        modelo.addColumn("Fecha");
        modelo.addColumn("Estatus");
        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();

        List<AutorizacionOrdenCompra1> proveedor = proveedorDAO.select();
        Tbl_Datoss.setModel(modelo);
        String[] dato = new String[6];
        for (int i = 0; i < proveedor.size(); i++) {
            dato[0] = Integer.toString(proveedor.get(i).getPK_codigo_autorizacion());
            dato[1] = proveedor.get(i).getCodigo_ordencompra();
            dato[2] = proveedor.get(i).getNombre_autorizacion();
            dato[3] = proveedor.get(i).getDepartamento_autorizacion();
            dato[4] = proveedor.get(i).getFecha_autorizacion();
            dato[5] = proveedor.get(i).getEstatus_autorizacion();

            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        
        }}
        
        public void buscar() {
        AutorizacionOrdenCompra1 proveedorAConsultar = new AutorizacionOrdenCompra1();
        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();
        proveedorAConsultar.setPK_codigo_autorizacion(Integer.parseInt(Txt_ID.getText()));
        proveedorAConsultar = proveedorDAO.query(proveedorAConsultar);
        txt_Idorden.setText(proveedorAConsultar.getCodigo_ordencompra());
        Txt_Autorizado.setText(proveedorAConsultar.getNombre_autorizacion());
        txt_puesto.setSelectedItem(proveedorAConsultar.getDepartamento_autorizacion());
        Txt_Fecha.setText(proveedorAConsultar.getFecha_autorizacion());
        Txt_estatus.setText(proveedorAConsultar.getEstatus_autorizacion());
        
        
        

    }

    public void limpiar() {
        Txt_ID.setText("");
        txt_Idorden.setText("");
        Txt_Autorizado.setText("");
        txt_puesto.setSelectedItem(null);
        Txt_Fecha.setText("");
        Txt_estatus.setText("");


    }


    public AutorizacionOrdenCompra() {
        initComponents();
        
        llenadoDeTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Pnl_datos2 = new javax.swing.JPanel();
        Lbl_codigo2 = new javax.swing.JLabel();
        Txt_ID = new javax.swing.JTextField();
        Lbl_nombre2 = new javax.swing.JLabel();
        Lbl_telefono2 = new javax.swing.JLabel();
        Lbl_nit2 = new javax.swing.JLabel();
        Txt_estatus = new javax.swing.JTextField();
        Btn_Guardar2 = new javax.swing.JButton();
        Btn_Modificar2 = new javax.swing.JButton();
        Btn_Eliminar2 = new javax.swing.JButton();
        Btn_Reporte5 = new javax.swing.JButton();
        Txt_Fecha = new javax.swing.JTextField();
        Lbl_direccion3 = new javax.swing.JLabel();
        txt_puesto = new javax.swing.JComboBox<>();
        Lbl_nombre4 = new javax.swing.JLabel();
        Txt_Autorizado = new javax.swing.JTextField();
        txt_Idorden = new javax.swing.JTextField();
        btnAgregarProveedor = new javax.swing.JButton();
        Btn_Reporte = new javax.swing.JButton();
        Pnl_detalle3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Tbl_Datoss = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Autorizacion Compra");
        setVisible(true);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Autorización de Orden de Compra");

        Pnl_datos2.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_datos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos AutorizacionOrdenCompra"));

        Lbl_codigo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_codigo2.setText("Codigo de Autorizacion:");

        Lbl_nombre2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre2.setText("Codigo Orden Compra:");

        Lbl_telefono2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_telefono2.setText("Fecha Autorizacion:");

        Lbl_nit2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nit2.setText("Estatus Autorizacion:");

        Btn_Guardar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Guardar2.setText("Guardar");
        Btn_Guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Guardar2ActionPerformed(evt);
            }
        });

        Btn_Modificar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Modificar2.setText("Modificar");
        Btn_Modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Modificar2ActionPerformed(evt);
            }
        });

        Btn_Eliminar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Eliminar2.setText("Eliminar");
        Btn_Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Eliminar2ActionPerformed(evt);
            }
        });

        Btn_Reporte5.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        Btn_Reporte5.setText("Buscar");
        Btn_Reporte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte5ActionPerformed(evt);
            }
        });

        Lbl_direccion3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion3.setText("Puesto: ");

        txt_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente General", "Jefe de departamento de Compras", "Jefe de area", "Gerente de Recursos Humanos", " ", " " }));

        Lbl_nombre4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre4.setText("Autorizado Por :");

        txt_Idorden.setEditable(false);
        txt_Idorden.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_Idorden.setBorder(null);
        txt_Idorden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_IdordenKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdordenKeyTyped(evt);
            }
        });

        btnAgregarProveedor.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnAgregarProveedor.setText("Agregar");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        Btn_Reporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte.setText("Reporte");
        Btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReporteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_datos2Layout = new javax.swing.GroupLayout(Pnl_datos2);
        Pnl_datos2.setLayout(Pnl_datos2Layout);
        Pnl_datos2Layout.setHorizontalGroup(
            Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Lbl_codigo2)
                                .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Lbl_nombre2)))
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lbl_nombre4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(Lbl_direccion3)))))
                        .addGap(39, 39, 39)
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Txt_Autorizado, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Txt_ID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(txt_Idorden, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAgregarProveedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Btn_Reporte5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txt_puesto, javax.swing.GroupLayout.Alignment.LEADING, 0, 223, Short.MAX_VALUE)
                                .addComponent(Txt_Fecha, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(Txt_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(Lbl_telefono2))
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addComponent(Btn_Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(Lbl_nit2)))))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        Pnl_datos2Layout.setVerticalGroup(
            Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Lbl_codigo2)
                        .addComponent(Txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Btn_Reporte5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre2)
                    .addComponent(txt_Idorden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProveedor))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre4)
                    .addComponent(Txt_Autorizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_direccion3))
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(Lbl_telefono2))
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_nit2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        Pnl_detalle3.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_detalle3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Autorizacion"));

        Tbl_Datoss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane5.setViewportView(Tbl_Datoss);

        javax.swing.GroupLayout Pnl_detalle3Layout = new javax.swing.GroupLayout(Pnl_detalle3);
        Pnl_detalle3.setLayout(Pnl_detalle3Layout);
        Pnl_detalle3Layout.setHorizontalGroup(
            Pnl_detalle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_detalle3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );
        Pnl_detalle3Layout.setVerticalGroup(
            Pnl_detalle3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_detalle3Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(154, 154, 154))
                    .addComponent(Pnl_detalle3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Pnl_datos2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(Pnl_datos2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pnl_detalle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Guardar2ActionPerformed
        // TODO add your handling code here:

        AutorizacionOrdenCompraDAO emisionchequeDAO = new AutorizacionOrdenCompraDAO();
        AutorizacionOrdenCompra1 insertar = new AutorizacionOrdenCompra1();

        insertar.setPK_codigo_autorizacion((int) Integer.parseInt(Txt_ID.getText()));
        insertar.setCodigo_ordencompra(txt_Idorden.getText());
        insertar.setNombre_autorizacion(Txt_Autorizado.getText());
        insertar.setDepartamento_autorizacion(txt_puesto.getSelectedItem().toString());
        insertar.setFecha_autorizacion(Txt_Fecha.getText());
        insertar.setEstatus_autorizacion(Txt_estatus.getText());

        emisionchequeDAO.insert(insertar);

        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_Guardar2ActionPerformed

    private void Btn_Modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Modificar2ActionPerformed
        // TODO add your handling code here:
       AutorizacionOrdenCompraDAO  proveedorDAO = new AutorizacionOrdenCompraDAO ();
       AutorizacionOrdenCompra1 proveedorAActualizar = new AutorizacionOrdenCompra1();
        proveedorAActualizar.setPK_codigo_autorizacion(Integer.parseInt(Txt_ID.getText()));
        proveedorAActualizar.setCodigo_ordencompra(txt_Idorden.getText());
        proveedorAActualizar.setNombre_autorizacion(Txt_Autorizado.getText());
        proveedorAActualizar.setDepartamento_autorizacion(txt_puesto.getSelectedItem().toString());
        proveedorAActualizar.setFecha_autorizacion(Txt_Fecha.getText());
        proveedorAActualizar.setEstatus_autorizacion(Txt_estatus.getText());

        proveedorDAO.update(proveedorAActualizar);
        JOptionPane.showMessageDialog(null, "Modificación Exitosa.");
        limpiar();
        llenadoDeTablas();
    }//GEN-LAST:event_Btn_Modificar2ActionPerformed

    private void Btn_Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Eliminar2ActionPerformed
        // TODO add your handling code here:
        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();
        AutorizacionOrdenCompra1 proveedorAEliminar = new AutorizacionOrdenCompra1();
        proveedorAEliminar.setPK_codigo_autorizacion(Integer.parseInt(Txt_ID.getText()));
        proveedorDAO.delete(proveedorAEliminar);
        JOptionPane.showMessageDialog(null, "Registro Eliminado.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_Eliminar2ActionPerformed

    private void Btn_Reporte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte5ActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_Btn_Reporte5ActionPerformed

    private void txt_IdordenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdordenKeyPressed

    }//GEN-LAST:event_txt_IdordenKeyPressed

    private void txt_IdordenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdordenKeyTyped

    }//GEN-LAST:event_txt_IdordenKeyTyped

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        // TODO add your handling code here:
        ListadoOrdenesCompras pro = new ListadoOrdenesCompras ();
        MDIComercial.jdpescritorio.add(pro);
        pro.toFront();
        pro.setVisible(true);
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed
private Connection connection = null;
    private void Btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReporteActionPerformed
        Map p = new HashMap();
        JasperReport report;
        JasperPrint print;

        try {
            connection = Conexion.getConnection();
            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                + "/src/main/java/Comercial/reportes/Aurorizacion.jrxml");
            print = JasperFillManager.fillReport(report, p, connection);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Reporte Mantenimiento Proveedor");
            view.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Btn_ReporteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Eliminar2;
    public javax.swing.JButton Btn_Guardar2;
    public javax.swing.JButton Btn_Modificar2;
    public javax.swing.JButton Btn_Reporte;
    public javax.swing.JButton Btn_Reporte5;
    private javax.swing.JLabel Lbl_codigo2;
    private javax.swing.JLabel Lbl_direccion3;
    private javax.swing.JLabel Lbl_nit2;
    private javax.swing.JLabel Lbl_nombre2;
    private javax.swing.JLabel Lbl_nombre4;
    private javax.swing.JLabel Lbl_telefono2;
    private javax.swing.JPanel Pnl_datos2;
    private javax.swing.JPanel Pnl_detalle3;
    private javax.swing.JTable Tbl_Datoss;
    public javax.swing.JTextField Txt_Autorizado;
    public javax.swing.JTextField Txt_Fecha;
    public javax.swing.JTextField Txt_ID;
    public javax.swing.JTextField Txt_estatus;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JTextField txt_Idorden;
    private javax.swing.JComboBox<String> txt_puesto;
    // End of variables declaration//GEN-END:variables
}
