/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Comercial.vista;

import Comercial.datos.ClienteDao;
import Comercial.datos.CobradorDao;
import Comercial.datos.Control_pago_VentaDao;
import Comercial.datos.Factura_VentaDao;
import Comercial.datos.Factura_VentaDao1;
import Comercial.datos.Registro_ventaDao;
import Comercial.datos.VendedorDao;
import Comercial.dominio.Cliente;
import Comercial.dominio.Cobrador;
import Comercial.dominio.Control_pago_Venta;
import Comercial.dominio.Factura_Venta;
import Comercial.dominio.Registro_venta;
import Comercial.dominio.Vendedor;
import java.io.File;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import seguridad.datos.BitacoraDao;
import seguridad.dominio.Bitacora;
import seguridad.vista.Aplicacion_Perfil;
import seguridad.vista.Login;

/**
 *
 * @author PERSONAL
 */
public class Control_Precios_vemta extends javax.swing.JInternalFrame {

   Control_pago_VentaDao Buscar3  = new  Control_pago_VentaDao();  

   Control_pago_Venta venta  = new  Control_pago_Venta();
 
  /**
     * Creates new form Proceso_Factura_venta
     */
   


public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
     
   modelo.addColumn("NUMEORO DE SERIE");
        modelo.addColumn("CODIGO SERVICIO");
        modelo.addColumn("PRECIO");
        modelo.addColumn("PRECIO CAMBIO");
        modelo.addColumn("FECHA DE EMISION");
        modelo.addColumn("ESTATUS PRECIO");
        

    
      
         Control_pago_VentaDao  ventasDAO = new  Control_pago_VentaDao ();

        List< Control_pago_Venta> ventas = ventasDAO.select();
//        List<Factura_Venta > ventas1 = ventasDAO1.select1();
        Jtfactura.setModel(modelo);
        String[] dato = new String[6];
        for (int i = 0; i < ventas.size(); i++) {
             dato[0] = (ventas.get(i).getNo_serie());
             dato[1] = ventas.get(i).getServicio();
             dato[2] = ventas.get(i).getPrecio();
             dato[3] = ventas.get(i).getPrecio_cambio();
             dato[4] = (ventas.get(i).getFecha());
             dato[5] = (ventas.get(i).getEstatus());
            
//             dato[12] = ventas1.get(i).getCantidad_servicio();
//              dato[13] = ventas1.get(i).getPrecio_servicio();
            System.out.println("vendedor:" + ventas);
            modelo.addRow(dato);
        }
    }        


public void buscarVendedor1() {
     
   venta.setNo_serie(Txt_numero1.getText());
   
venta=Buscar3.query(venta);

Txt_servicio.setText(venta.getServicio());
Txt_precio.setText(venta.getPrecio());
cambio_precio.setText(venta.getPrecio_cambio());

txt_estatus.setText(venta.getEstatus());
Txt_fecha1.setText(venta.getFecha());





}

public Control_Precios_vemta() {
        initComponents();
     
     llenadoDeTablas();
    
        
        
      
}
public void limpiar() {
        
        txt_estatus.setText("");
        
        Txt_fecha1.setText("");
        Txt_servicio.setText("");
      Txt_numero1.setText("");
        Txt_precio.setText("");
       cambio_precio.setText("");
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Txt_servicio = new javax.swing.JTextField();
        Btn_Buscar = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel12 = new javax.swing.JLabel();
        Txt_fecha1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_precio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_estatus = new javax.swing.JTextField();
        Btn_reporte = new javax.swing.JButton();
        Txt_numero1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cambio_precio = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Jtfactura = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel21.setText("CONTROL DE PRECIOS VENTA");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        jLabel2.setText("NO. CONTROL DE PRECIOS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, 20));

        jLabel13.setText("CODIGO SERVICIO");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));
        jPanel2.add(Txt_servicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 110, -1));

        Btn_Buscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Buscar.setText("Buscar");
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 80, 100, 30));

        jToggleButton1.setBackground(new java.awt.Color(255, 255, 102));
        jToggleButton1.setText("Guardar");
        jToggleButton1.setBorderPainted(false);
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        jToggleButton2.setText("Modificar");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        jToggleButton3.setText("Eliminar");
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, -1, -1));

        jLabel12.setText("FECHA");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel2.add(Txt_fecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 109, 20));

        jLabel6.setText("PRECIO");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel2.add(Txt_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 109, 20));

        jLabel7.setText("Estatus");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, -1));
        jPanel2.add(txt_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 110, -1));

        Btn_reporte.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_reporte.setText("Reporte");
        Btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_reporteActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 90, 20));
        jPanel2.add(Txt_numero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 110, -1));

        jLabel1.setText("CAMBIO DE PRECIO");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, -1, 20));
        jPanel2.add(cambio_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 80, -1));

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 190, 90, 30));

        jButton3.setText("Modificar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(185, 190, 100, 40));

        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 190, 100, 40));

        Jtfactura.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "FECHA", "SERVIVO", "CANTIDAD"
            }
        ));
        jScrollPane2.setViewportView(Jtfactura);

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Ayuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 668, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    private void Btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_reporteActionPerformed
        //  Map p = new HashMap();
        //        JasperReport report;
        //        JasperPrint print;
        //
        //        try {
            //            connection = Conexion.getConnection();
            //            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                //                    + "/src/main/java/Comercial/reportes/MantenimientoCliente.jrxml");
            //            print = JasperFillManager.fillReport(report, p, connection);
            //            JasperViewer view = new JasperViewer(print, false);
            //            view.setTitle("cliente ");
            //            view.setVisible(true);
            //
            //        } catch (Exception e) {
            //            e.printStackTrace();
            //        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_reporteActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
buscarVendedor1();


// TODO add your handling code here:
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
  Control_pago_VentaDao  Control_pago_VentaDao  = new  Control_pago_VentaDao();

         Control_pago_Venta AInser = new  Control_pago_Venta();
      
      
        AInser.setNo_serie(Txt_servicio.getText());
       
        AInser.setServicio(Txt_servicio.getText());
        AInser.setPrecio(Txt_precio.getText());
        AInser.setPrecio_cambio(cambio_precio.getText());
        AInser.setFecha(Txt_fecha1.getText());
        AInser.setEstatus(txt_estatus.getText());
       

        Control_pago_VentaDao.insert(AInser);
        llenadoDeTablas();
        limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
  Control_pago_VentaDao  Control_pago_VentaDao  = new  Control_pago_VentaDao();

         Control_pago_Venta AInser = new  Control_pago_Venta();
      
      
        AInser.setNo_serie(Txt_servicio.getText());
       
        AInser.setServicio(Txt_servicio.getText());
        AInser.setPrecio(Txt_precio.getText());
        AInser.setPrecio_cambio(cambio_precio.getText());
        AInser.setFecha(Txt_fecha1.getText());
        AInser.setEstatus(txt_estatus.getText());
       

        Control_pago_VentaDao.update(AInser);
        llenadoDeTablas();
        limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed

 Control_pago_VentaDao  Control_pago_VentaDao  = new  Control_pago_VentaDao();

         Control_pago_Venta AInser = new  Control_pago_Venta();
      
      
        AInser.setNo_serie(Txt_servicio.getText());
       
        AInser.setServicio(Txt_servicio.getText());
        AInser.setPrecio(Txt_precio.getText());
        AInser.setPrecio_cambio(cambio_precio.getText());
        AInser.setFecha(Txt_fecha1.getText());
        AInser.setEstatus(txt_estatus.getText());
       

        Control_pago_VentaDao.delete(AInser);
            llenadoDeTablas();
            limpiar();
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if ((new File("src\\main\\java\\Comercial\\reportes\\control.chm")).exists()) {
                Process p = Runtime
                .getRuntime()
                .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\Comercial\\reportes\\control.chm");
                p.waitFor();
            } else {
                JOptionPane.showMessageDialog(null, "La ayuda no Fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
Control_pago_VentaDao  Control_pago_VentaDao  = new  Control_pago_VentaDao();

         Control_pago_Venta AInser = new  Control_pago_Venta();
      
      
        AInser.setNo_serie(Txt_servicio.getText());
       
        AInser.setServicio(Txt_servicio.getText());
        AInser.setPrecio(Txt_precio.getText());
        AInser.setPrecio_cambio(cambio_precio.getText());
        AInser.setFecha(Txt_fecha1.getText());
        AInser.setEstatus(txt_estatus.getText());
       

        Control_pago_VentaDao.insert(AInser);
        llenadoDeTablas();
        limpiar();
         BitacoraDao BitacoraDAO = new BitacoraDao();
        
                Bitacora Insertar = new Bitacora();
                Insertar.setId_Usuario(Login.usuarioComercial);
                Insertar.setAccion("Insertar");
        
                Insertar.setCodigoAplicacion("3003");
                Insertar.setModulo("3000");
        
                try {
                        BitacoraDAO.insert(Insertar);
                    } catch (UnknownHostException ex) {
                        Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
                    }
      

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

 Control_pago_VentaDao  Control_pago_VentaDao  = new  Control_pago_VentaDao();

         Control_pago_Venta AInser = new  Control_pago_Venta();
      
      
        AInser.setNo_serie(Txt_servicio.getText());
       
        AInser.setServicio(Txt_servicio.getText());
        AInser.setPrecio(Txt_precio.getText());
        AInser.setPrecio_cambio(cambio_precio.getText());
        AInser.setFecha(Txt_fecha1.getText());
        AInser.setEstatus(txt_estatus.getText());
       

        Control_pago_VentaDao.delete(AInser);
            llenadoDeTablas();
            limpiar();

             BitacoraDao BitacoraDAO = new BitacoraDao();
        
                Bitacora Insertar = new Bitacora();
                Insertar.setId_Usuario(Login.usuarioComercial);
                Insertar.setAccion("Eliminar");
        
                Insertar.setCodigoAplicacion("3003");
                Insertar.setModulo("3000");
        
                try {
                        BitacoraDAO.insert(Insertar);
                    } catch (UnknownHostException ex) {
                        Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
                    }
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
Control_pago_VentaDao  Control_pago_VentaDao  = new  Control_pago_VentaDao();

         Control_pago_Venta AInser = new  Control_pago_Venta();
      
      
        AInser.setNo_serie(Txt_servicio.getText());
       
        AInser.setServicio(Txt_servicio.getText());
        AInser.setPrecio(Txt_precio.getText());
        AInser.setPrecio_cambio(cambio_precio.getText());
        AInser.setFecha(Txt_fecha1.getText());
        AInser.setEstatus(txt_estatus.getText());
       

        Control_pago_VentaDao.update(AInser);
        llenadoDeTablas();
        limpiar();
        
          BitacoraDao BitacoraDAO = new BitacoraDao();
        
                Bitacora Insertar = new Bitacora();
                Insertar.setId_Usuario(Login.usuarioComercial);
                Insertar.setAccion("Eliminar");
        
                Insertar.setCodigoAplicacion("3003");
                Insertar.setModulo("3000");
        
                try {
                        BitacoraDAO.insert(Insertar);
                    } catch (UnknownHostException ex) {
                        Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
                    }
      

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_reporte;
    private javax.swing.JTable Jtfactura;
    private javax.swing.JTextField Txt_fecha1;
    private javax.swing.JTextField Txt_numero1;
    private javax.swing.JTextField Txt_precio;
    private javax.swing.JTextField Txt_servicio;
    private javax.swing.JTextField cambio_precio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JTextField txt_estatus;
    // End of variables declaration//GEN-END:variables
}
