
/*
 * 
 *
 * @author SipaqueRitaMaria
 */
package Comercial.vista;


import Comercial.datos.OrdenCompraDAO;
import Comercial.dominio.OrdenCompra;
import java.awt.Color;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class ListadoOrdenesCompras extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;

    /** Creates new form clientes */
    
   public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("No.Factura");
        modelo.addColumn("ID BODEGA");
        modelo.addColumn("ID PROVEEDOR");
        modelo.addColumn("FECHA EMISION");
        modelo.addColumn("FECHA VENCIMIENTO");
        modelo.addColumn("FORMA PAGO");
        modelo.addColumn("Estado");
        OrdenCompraDAO proveedorDAO = new OrdenCompraDAO();

        List<OrdenCompra> proveedor = proveedorDAO.select();
        tborden.setModel(modelo);
        String[] dato = new String[7];
        for (int i = 0; i < proveedor.size(); i++) {
            dato[0] = Integer.toString(proveedor.get(i).getPK_codigo_ordencompra());
            dato[1] = proveedor.get(i).getPK_codigo_bodega();
            dato[2] = proveedor.get(i).getCodigo_proveedor();
            dato[3] = proveedor.get(i).getFecha_emision();
            dato[4] = proveedor.get(i).getFecha_vencimiento();
            dato[5] = proveedor.get(i).getCodigo_pago();
            dato[6] = proveedor.get(i).getEstatus_ordecompra();
            modelo.addRow(dato);
        }
        }
    public ListadoOrdenesCompras() {
        initComponents();
        llenadoDeTablas();
        
        
    
       
       
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tborden = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        jPopupMenu1.setForeground(new java.awt.Color(204, 0, 204));

        mnenviar.setText("Enviar Datos");
        mnenviar.setToolTipText("");
        mnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviar);

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("ListadoOrdenesCompra");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tborden.setComponentPopupMenu(jPopupMenu1);
        tborden.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tborden.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbordenAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tbordenAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tborden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbordenMouseClicked(evt);
            }
        });
        tborden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbordenKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tborden);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Listado Ordenes Compra");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 555, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarActionPerformed
// TODO add your handling code here:
    
      String cod="", uno="", dos="" ;
    int fila = tborden.getSelectedRow();
    String cod1="", cod2="", cod3="",cod4="",cod5="",cod6="",cod7="" ;
    int fila2 = tborden.getSelectedRow();
   
    try {
        if(fila==-1)
        {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");
                  
        }
        else
        {
         cod =  (String)tborden.getValueAt(fila, 0);
       
         
        AutorizacionOrdenCompra.txt_Idorden.setDisabledTextColor(Color.blue);
        AutorizacionOrdenCompra.txt_Idorden.setText(cod);
       
        
         
         this.dispose();
     }
     } catch (Exception e) {
       }  

    
     try {
        if(fila2==-1)
        {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");
                  
        }
        else
        {
         cod1 =  (String)tborden.getValueAt(fila2, 0);
         cod2 =  (String)tborden.getValueAt(fila2, 1);
         cod3 =  (String)tborden.getValueAt(fila2, 2);
         cod4=  (String)tborden.getValueAt(fila2, 3);
       cod5 =  (String)tborden.getValueAt(fila2, 4);
       cod6 =  (String)tborden.getValueAt(fila2, 5);
       cod7 =  (String)tborden.getValueAt(fila2, 6);
         
        ProcesoDevolucionCompra.txt_IdProveedor.setDisabledTextColor(Color.blue);
      ProcesoDevolucionCompra.txt_IdProveedor.setText(cod1);
       
      ProcesoDevolucionCompra.txt_IdProveedor.setDisabledTextColor(Color.blue);
      ProcesoDevolucionCompra.txt_IdProveedor.setText(cod2);
        
      ProcesoDevolucionCompra.txt_IdBodega.setDisabledTextColor(Color.blue);
      ProcesoDevolucionCompra.txt_IdBodega.setText(cod3);
      
     
     
      
      
      
         this.dispose();
     }
     } catch (Exception e) {
        
}  

    
    
    
}//GEN-LAST:event_mnenviarActionPerformed

    private void tbordenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbordenMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbordenMouseClicked

    private void tbordenAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbordenAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbordenAncestorMoved

    private void tbordenAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbordenAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbordenAncestorAdded

    private void tbordenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbordenKeyPressed
        // TODO add your handling code here:
        
        
     
        
        
    }//GEN-LAST:event_tbordenKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnenviar;
    private javax.swing.JTable tborden;
    // End of variables declaration//GEN-END:variables
//    conectar cc= new conectar();
//    Connection cn = cc.conexion();
}
