
/*
 * 
 *
 * @author SipaqueRitaMaria
 */
package Comercial.vista;



import Comercial.dominio.FormaPago;
import Comercial.datos.FormaPagoDAO;
import Comercial.dominio.Producto;
import java.awt.Color;
import java.sql.*;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import Comercial.datos.Conexion;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

public class Mantenimiento_FormaPago extends javax.swing.JInternalFrame {
    DefaultTableModel modelo;

    /** Creates new form clientes */
    
   
        public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("CodigoProveedor");
        modelo.addColumn("Transaccion");
        modelo.addColumn("Forma");
        modelo.addColumn("Dias");
        modelo.addColumn("Fecha");
        modelo.addColumn("Estatus");
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();

        List<FormaPago> proveedor = proveedorDAO.select();
        tbpago.setModel(modelo);
        String[] dato = new String[7];
        for (int i = 0; i < proveedor.size(); i++) {
            dato[0] = Integer.toString(proveedor.get(i).getPK_codigo_pago());
            dato[1] = proveedor.get(i).getCodigo_proveedor();
            dato[2] = proveedor.get(i).getTipo_pago();
            dato[3] = proveedor.get(i).getForma_pago();
            dato[4] = proveedor.get(i).getDias_pago();
            dato[5] = proveedor.get(i).getFecha_pago();
            dato[6] = proveedor.get(i).getEstatus_pago();

            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        
        }}
        
        public void buscar() {
        FormaPago proveedorAConsultar = new FormaPago();
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();
        proveedorAConsultar.setPK_codigo_pago(Integer.parseInt(Txt_ID.getText()));
        proveedorAConsultar = proveedorDAO.query(proveedorAConsultar);
        txt_IdProveedor.setText(proveedorAConsultar.getCodigo_proveedor());
        txt_tipopago.setSelectedItem(proveedorAConsultar.getTipo_pago());
        txt_formapago.setSelectedItem(proveedorAConsultar.getForma_pago());
        txt_dias.setSelectedItem(proveedorAConsultar.getDias_pago());
        Txt_Fecha.setText(proveedorAConsultar.getFecha_pago());

        Txt_estatus.setText(proveedorAConsultar.getEstatus_pago());

    }

    public void limpiar() {
        Txt_ID.setText("");
        txt_IdProveedor.setText("");
        txt_tipopago.setSelectedItem(null);
        txt_formapago.setSelectedItem(null);
         txt_dias.setSelectedItem(null);
                
        Txt_Fecha.setText("");
        Txt_estatus.setText("");


    }
        
    public Mantenimiento_FormaPago() {
        initComponents();
        llenadoDeTablas();
        
        
    
       
       
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        mnenviar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Pnl_datos2 = new javax.swing.JPanel();
        Lbl_codigo2 = new javax.swing.JLabel();
        Txt_ID = new javax.swing.JTextField();
        Lbl_nombre2 = new javax.swing.JLabel();
        Lbl_direccion2 = new javax.swing.JLabel();
        Lbl_telefono2 = new javax.swing.JLabel();
        Lbl_nit2 = new javax.swing.JLabel();
        Txt_estatus = new javax.swing.JTextField();
        Btn_Reporte4 = new javax.swing.JButton();
        Btn_Guardar2 = new javax.swing.JButton();
        Btn_Modificar2 = new javax.swing.JButton();
        Btn_Eliminar2 = new javax.swing.JButton();
        Btn_Reporte5 = new javax.swing.JButton();
        Txt_Fecha = new javax.swing.JTextField();
        txt_dias = new javax.swing.JComboBox<>();
        Lbl_direccion3 = new javax.swing.JLabel();
        txt_formapago = new javax.swing.JComboBox<>();
        Lbl_nombre4 = new javax.swing.JLabel();
        txt_tipopago = new javax.swing.JComboBox<>();
        txt_IdProveedor = new javax.swing.JTextField();
        btnAgregarProveedor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpago = new javax.swing.JTable();
        Btn_Ayuda = new javax.swing.JButton();

        jPopupMenu1.setForeground(new java.awt.Color(204, 0, 204));

        mnenviar.setBackground(new java.awt.Color(153, 255, 153));
        mnenviar.setText("Enviar Datos");
        mnenviar.setToolTipText("");
        mnenviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnenviarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(mnenviar);

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Forma Pago");
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mantenimiento Forma Pago");

        Pnl_datos2.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_datos2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Forma Pago"));

        Lbl_codigo2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_codigo2.setText("Codigo Forma Pago:");

        Lbl_nombre2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre2.setText("Codigo Proveeedor:");

        Lbl_direccion2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion2.setText("Dias pago:");

        Lbl_telefono2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_telefono2.setText("Fecha Pago:");

        Lbl_nit2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nit2.setText("Estatus Forma Pago:");

        Btn_Reporte4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte4.setText("Reporte");
        Btn_Reporte4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte4ActionPerformed(evt);
            }
        });

        Btn_Guardar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Guardar2.setText("Guardar");
        Btn_Guardar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Guardar2ActionPerformed(evt);
            }
        });

        Btn_Modificar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Modificar2.setText("Modificar");
        Btn_Modificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Modificar2ActionPerformed(evt);
            }
        });

        Btn_Eliminar2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Eliminar2.setText("Eliminar");
        Btn_Eliminar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Eliminar2ActionPerformed(evt);
            }
        });

        Btn_Reporte5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte5.setText("Buscar");
        Btn_Reporte5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte5ActionPerformed(evt);
            }
        });

        txt_dias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0 dias", "15 dias", "30 dias", "60 dias", " " }));

        Lbl_direccion3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion3.setText("Forma de pago:");

        txt_formapago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Contado", "Credito" }));

        Lbl_nombre4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre4.setText("Tipo de Pago:");

        txt_tipopago.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Factura Compra", "Orden de Compra", "Resepcion de Compra", "Devolucion de Compra", " " }));

        txt_IdProveedor.setEditable(false);
        txt_IdProveedor.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_IdProveedor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt_IdProveedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_IdProveedorKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_IdProveedorKeyTyped(evt);
            }
        });

        btnAgregarProveedor.setText("Agregar");
        btnAgregarProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarProveedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_datos2Layout = new javax.swing.GroupLayout(Pnl_datos2);
        Pnl_datos2.setLayout(Pnl_datos2Layout);
        Pnl_datos2Layout.setHorizontalGroup(
            Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_nombre2)
                    .addComponent(Lbl_codigo2))
                .addGap(44, 44, 44)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(Btn_Reporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarProveedor)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addComponent(Btn_Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Btn_Modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(Btn_Reporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pnl_datos2Layout.createSequentialGroup()
                                    .addComponent(Lbl_nit2)
                                    .addGap(18, 18, 18)
                                    .addComponent(Txt_estatus))
                                .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                    .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Lbl_telefono2)
                                        .addComponent(Lbl_direccion2))
                                    .addGap(302, 302, 302)))))
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_nombre4)
                            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Lbl_direccion3)))
                        .addGap(60, 60, 60)
                        .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Pnl_datos2Layout.setVerticalGroup(
            Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_codigo2)
                    .addComponent(Txt_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre2)
                    .addComponent(txt_IdProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProveedor))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre4)
                    .addComponent(txt_tipopago, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_formapago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_direccion3))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_direccion2)
                    .addComponent(txt_dias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(Lbl_telefono2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datos2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txt_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nit2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_estatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Guardar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Modificar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );

        tbpago.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbpago.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbpagoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tbpagoAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tbpago.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbpagoMouseClicked(evt);
            }
        });
        tbpago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbpagoKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbpago);

        Btn_Ayuda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Ayuda.setText("Ayuda");
        Btn_Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AyudaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pnl_datos2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Ayuda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pnl_datos2, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void mnenviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnenviarActionPerformed
// TODO add your handling code here:
    String cod="";
    int fila = tbpago.getSelectedRow();
    try {
        if(fila==-1)
        {
            JOptionPane.showMessageDialog(null, "No ha seleccionado ningun dato");
                  
        }
        else
        {
         cod =  (String)tbpago.getValueAt(fila, 0);
         
         
         Porceso_FacturaCompras.txt_CodigoPago.setDisabledTextColor(Color.blue);
         Porceso_FacturaCompras.txt_CodigoPago.setText(cod);
         
         
         
         
         
         this.dispose();
         
        }
    } catch (Exception e) {
    }
}//GEN-LAST:event_mnenviarActionPerformed

    private void Btn_Reporte4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte4ActionPerformed

    }//GEN-LAST:event_Btn_Reporte4ActionPerformed

    private void Btn_Guardar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Guardar2ActionPerformed
        // TODO add your handling code here:

        FormaPagoDAO emisionchequeDAO = new FormaPagoDAO();
        FormaPago insertar = new FormaPago();

        insertar.setPK_codigo_pago((int) Integer.parseInt(Txt_ID.getText()));
        insertar.setCodigo_proveedor(txt_IdProveedor.getText());
        insertar.setTipo_pago(txt_tipopago.getSelectedItem().toString());
        insertar.setForma_pago(txt_formapago.getSelectedItem().toString());
        insertar.setDias_pago(txt_dias.getSelectedItem().toString());

        insertar.setFecha_pago(Txt_Fecha.getText());

        insertar.setEstatus_pago(Txt_estatus.getText());

        emisionchequeDAO.insert(insertar);

        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_Guardar2ActionPerformed

    private void Btn_Modificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Modificar2ActionPerformed
        // TODO add your handling code here:
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();
        FormaPago proveedorAActualizar = new FormaPago();
        proveedorAActualizar.setPK_codigo_pago(Integer.parseInt(Txt_ID.getText()));
        proveedorAActualizar.setCodigo_proveedor(txt_IdProveedor.getText());
        proveedorAActualizar.setTipo_pago(txt_tipopago.getSelectedItem().toString());
        proveedorAActualizar.setForma_pago(txt_formapago.getSelectedItem().toString());
        proveedorAActualizar.setDias_pago(txt_dias.getSelectedItem().toString());
        proveedorAActualizar.setFecha_pago(Txt_Fecha.getText());
        proveedorAActualizar.setEstatus_pago(Txt_estatus.getText());

        proveedorDAO.update(proveedorAActualizar);
        JOptionPane.showMessageDialog(null, "Modificación Exitosa.");
        limpiar();
        llenadoDeTablas();
    }//GEN-LAST:event_Btn_Modificar2ActionPerformed

    private void Btn_Eliminar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Eliminar2ActionPerformed
        // TODO add your handling code here:
        FormaPagoDAO proveedorDAO = new FormaPagoDAO();
        FormaPago proveedorAEliminar = new FormaPago();
        proveedorAEliminar.setPK_codigo_pago(Integer.parseInt(Txt_ID.getText()));
        proveedorDAO.delete(proveedorAEliminar);
        JOptionPane.showMessageDialog(null, "Registro Eliminado.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_Eliminar2ActionPerformed

    private void Btn_Reporte5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte5ActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_Btn_Reporte5ActionPerformed

    private void txt_IdProveedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdProveedorKeyPressed

    }//GEN-LAST:event_txt_IdProveedorKeyPressed

    private void txt_IdProveedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_IdProveedorKeyTyped

    }//GEN-LAST:event_txt_IdProveedorKeyTyped

    private void tbpagoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbpagoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoAncestorAdded

    private void tbpagoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbpagoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoAncestorMoved

    private void tbpagoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbpagoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoMouseClicked

    private void tbpagoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbpagoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbpagoKeyPressed

    private void btnAgregarProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarProveedorActionPerformed
        // TODO add your handling code here:
        ListadoProveedor pro = new ListadoProveedor();
        MDIComercial.jdpescritorio.add(pro);
        pro.toFront();
        pro.setVisible(true);
    }//GEN-LAST:event_btnAgregarProveedorActionPerformed

    private void Btn_AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AyudaActionPerformed

        try {
            if ((new File("src\\main\\java\\Comercial\\reportes\\AyudaSi.chm")).exists()) {
                Process p = Runtime
                .getRuntime()
                .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\Comercial\\reportes\\AyudaSi.chm");
                p.waitFor();
            } else {
                JOptionPane.showMessageDialog(null, "La ayuda no Fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_Btn_AyudaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Ayuda;
    public javax.swing.JButton Btn_Eliminar2;
    public javax.swing.JButton Btn_Guardar2;
    public javax.swing.JButton Btn_Modificar2;
    public javax.swing.JButton Btn_Reporte4;
    public javax.swing.JButton Btn_Reporte5;
    private javax.swing.JLabel Lbl_codigo2;
    private javax.swing.JLabel Lbl_direccion2;
    private javax.swing.JLabel Lbl_direccion3;
    private javax.swing.JLabel Lbl_nit2;
    private javax.swing.JLabel Lbl_nombre2;
    private javax.swing.JLabel Lbl_nombre4;
    private javax.swing.JLabel Lbl_telefono2;
    private javax.swing.JPanel Pnl_datos2;
    public javax.swing.JTextField Txt_Fecha;
    public javax.swing.JTextField Txt_ID;
    public javax.swing.JTextField Txt_estatus;
    private javax.swing.JButton btnAgregarProveedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem mnenviar;
    private javax.swing.JTable tbpago;
    public static javax.swing.JTextField txt_IdProveedor;
    private javax.swing.JComboBox<String> txt_dias;
    private javax.swing.JComboBox<String> txt_formapago;
    private javax.swing.JComboBox<String> txt_tipopago;
    // End of variables declaration//GEN-END:variables
//    conectar cc= new conectar();
//    Connection cn = cc.conexion();
}
