package Comercial.vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import Comercial.datos.VendedorDao;
import Comercial.dominio.Vendedor;
import java.io.File;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import seguridad.datos.BitacoraDao;
import seguridad.dominio.Bitacora;
import seguridad.vista.Aplicacion_Perfil;
import seguridad.vista.GenerarPermisos;
import seguridad.vista.Login;
import seguridad.vista.MDI_Components;

/**
 *
 * @author PERSONAL
 */
public class Mantenimiento_Vendedor extends javax.swing.JInternalFrame {

    int codigoAplicacion = 3001;

//    void habilitarAcciones() {
//
//        int codigoAplicacion = 3001;
//        var usuario = Login.usuarioComercial;
//
//        btnAgregar.setEnabled(false);
//        btnModificar.setEnabled(false);
//        btnEliminar.setEnabled(false);
//        btnBuscar.setEnabled(false);
//
//        GenerarPermisos permisos = new GenerarPermisos();
//
//        String[] permisosApp = new String[4];
//
//        for (int i = 0; i < 4; i++) {
//            permisosApp[i] = permisos.getAccionesAplicacion(codigoAplicacion, usuario)[i];
//        }
//
//        if (permisosApp[0].equals("1")) {
//            btnAgregar.setEnabled(true);
//        }
//        if (permisosApp[1].equals("1")) {
//            btnBuscar.setEnabled(true);
//        }
//        if (permisosApp[2].equals("1")) {
//            btnModificar.setEnabled(true);
//        }
//        if (permisosApp[3].equals("1")) {
//            btnEliminar.setEnabled(true);
//        }
//    }
    public void llenadoDeTablas() {
        /**
         *
         * creaccion de la tabla de de titulos
         */
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codico Vendedor");
        modelo.addColumn("Nombre Vendedor");

        modelo.addColumn("Estatus Vendedor");

        VendedorDao ventasDAO = new VendedorDao();

        List<Vendedor> ventas = ventasDAO.select();
        JtProductos1.setModel(modelo);
        String[] dato = new String[8];
        for (int i = 0; i < ventas.size(); i++) {
            dato[0] = (ventas.get(i).getCodigo_Vendedor());
            dato[1] = ventas.get(i).getNombre_Vendedor();

            dato[2] = (ventas.get(i).getEstatus_Vendedor());

            System.out.println("vendedor:" + ventas);
            modelo.addRow(dato);
        }
    }

    public void buscarVendedor() {

        VendedorDao Clientes = new VendedorDao();

        Vendedor Buscar = new Vendedor();
        Buscar.setCodigo_Vendedor(Txt_codigo.getText());
        Buscar = Clientes.query(Buscar);
        Txt_nombre.setText(Buscar.getNombre_Vendedor());

        Txt_estatus.setText(Buscar.getEstatus_Vendedor());

    }

    public void limpiar() {
        Txt_codigo.setText("");
        Txt_nombre.setText("");

        Txt_estatus.setText("");

    }

    /**
     * Creates new form Mantenimiento_Cliente
     */
    public Mantenimiento_Vendedor() {
        int codigoAplicacion = 3001;
        initComponents();
//        habilitarAcciones();
        llenadoDeTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        Btn_Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btn_Eliminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Btn_Agregar = new javax.swing.JButton();
        Txt_codigo = new javax.swing.JTextField();
        Txt_nombre = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtProductos1 = new javax.swing.JTable();
        Txt_estatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Btn_reporte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Btn_Buscar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimieto Cliente\n");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Modificar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Modificar.setText("Modificar");
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 90, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Mantenimiento Vendedor");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 11, -1, -1));

        Btn_Eliminar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 80, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Codigo Vendedor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 81, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Cliente Vendedor");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 113, -1, -1));

        Btn_Agregar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Agregar.setText("Guardar");
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(63, 210, 100, 30));

        Txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_codigoActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 78, 150, -1));
        getContentPane().add(Txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 110, 150, -1));

        JtProductos1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        JtProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtProductos1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 278, 540, 138));

        Txt_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 149, 150, -1));

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Ayuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(452, 14, 100, 30));

        Btn_reporte.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_reporte.setText("Reporte");
        Btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_reporteActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, 90, 30));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 136, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Btn_Buscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Buscar.setText("Buscar");
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Estatus Vendedor");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addContainerGap(317, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Btn_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 440, 120));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed

        VendedorDao dao = new VendedorDao();

        Vendedor modi = new Vendedor();

        modi.setCodigo_Vendedor(Txt_codigo.getText());
        modi.setNombre_Vendedor(Txt_nombre.getText());

        modi.setEstatus_Vendedor(Txt_estatus.getText());

        dao.update(modi);
        llenadoDeTablas();
        limpiar();
        BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();

        Insertar.setAccion("Modificar");
        Insertar.setId_Usuario(Login.usuarioComercial);
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();
        Insertar.setCodigoAplicacion("3001");
        Insertar.setModulo("3000");

        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }


        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ModificarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
//
        VendedorDao acreedor = new VendedorDao();

        Vendedor vendedorAEliminar = new Vendedor();
        vendedorAEliminar.setCodigo_Vendedor(Txt_codigo.getText());
        vendedorAEliminar.setNombre_Vendedor(Txt_nombre.getText());

        vendedorAEliminar.setEstatus_Vendedor(Txt_estatus.getText());

        acreedor.delete(vendedorAEliminar);
        llenadoDeTablas();
  
       
      limpiar();

BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();

        Insertar.setAccion("Eliminar");
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();
        Insertar.setCodigoAplicacion("3001");
        Insertar.setModulo("3003");
        Insertar.setId_Usuario(Login.usuarioComercial);
        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        buscarVendedor();
        BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();

        Insertar.setAccion("Buscar");
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();
        Insertar.setCodigoAplicacion("3001");
        Insertar.setModulo("3003");
        Insertar.setId_Usuario(Login.usuarioComercial);
        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }

//        buscarVendedor();
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed

////        GenerarPermisos permisos = new GenerarPermisos();
////        MDI_Components mdi_Components = new MDI_Components();
////
////        String id = "0";
        VendedorDao ClienteDAO = new VendedorDao();

        Vendedor AInsertar = new Vendedor();
        AInsertar.setCodigo_Vendedor(Txt_codigo.getText());
        AInsertar.setNombre_Vendedor(Txt_nombre.getText());

        AInsertar.setEstatus_Vendedor(Txt_estatus.getText());

        ClienteDAO.insert(AInsertar);

        llenadoDeTablas();
        limpiar();
        BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();
        Insertar.setId_Usuario(Login.usuarioComercial);
        Insertar.setAccion("Insertar");

        Insertar.setCodigoAplicacion("3003");
        Insertar.setModulo("3000");

        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if ((new File("src\\main\\java\\Comercial\\reportes\\vendedor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\Comercial\\\\reportes\\vendedor.chm");
                p.waitFor();
            } else {
                JOptionPane.showMessageDialog(null, "La ayuda no Fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_estatusActionPerformed
    private Connection connection = null;
    private void Btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_reporteActionPerformed
//  Map p = new HashMap();
//        JasperReport report;
//        JasperPrint print;
//
//        try {
//            connection = Conexion.getConnection();
//            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
//                    + "/src/main/java/Comercial/reportes/MantenimientoCliente.jrxml");
//            print = JasperFillManager.fillReport(report, p, connection);
//            JasperViewer view = new JasperViewer(print, false);
//            view.setTitle("cliente ");
//            view.setVisible(true);
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_reporteActionPerformed

    private void Txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_codigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Modificar;
    private javax.swing.JButton Btn_reporte;
    private javax.swing.JTable JtProductos1;
    private javax.swing.JTextField Txt_codigo;
    private javax.swing.JTextField Txt_estatus;
    private javax.swing.JTextField Txt_nombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
