package Comercial.vista;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



import Comercial.datos.ClienteDao;
import Comercial.dominio.Cliente;
import java.io.File;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import seguridad.datos.BitacoraDao;
import seguridad.dominio.Bitacora;
import seguridad.vista.Aplicacion_Perfil;
import seguridad.vista.GenerarPermisos;
import seguridad.vista.Login;
import seguridad.vista.MDI_Components;

/**
 *
 * @author PERSONAL
 */
public class Mantenimiento_Cliente extends javax.swing.JInternalFrame {

    int codigoAplicacion = 3001;

//    void habilitarAcciones() {
//
//        int codigoAplicacion = 3001;
//        var usuario = Login.usuarioComercial;
//
//        btnAgregar.setEnabled(false);
//        btnModificar.setEnabled(false);
//        btnEliminar.setEnabled(false);
//        btnBuscar.setEnabled(false);
//
//        GenerarPermisos permisos = new GenerarPermisos();
//
//        String[] permisosApp = new String[4];
//
//        for (int i = 0; i < 4; i++) {
//            permisosApp[i] = permisos.getAccionesAplicacion(codigoAplicacion, usuario)[i];
//        }
//
//        if (permisosApp[0].equals("1")) {
//            btnAgregar.setEnabled(true);
//        }
//        if (permisosApp[1].equals("1")) {
//            btnBuscar.setEnabled(true);
//        }
//        if (permisosApp[2].equals("1")) {
//            btnModificar.setEnabled(true);
//        }
//        if (permisosApp[3].equals("1")) {
//            btnEliminar.setEnabled(true);
//        }
//    }

    public void llenadoDeTablas() {
        /**
         *
         * creaccion de la tabla de de titulos
         */
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codico Cliente");
        modelo.addColumn("Nombre Cliente");
        modelo.addColumn("Direccion Cliente");
        modelo.addColumn("telefono Cliente");

        modelo.addColumn("Nit Cliente");
        modelo.addColumn("Email Cliente");
           modelo.addColumn("Saldo Cliente");
              modelo.addColumn("Cuenta Cliente");


        modelo.addColumn("Estatus Cliente");
      

        ClienteDao ventasDAO = new ClienteDao();

        List<Cliente> ventas = ventasDAO.select();
        JtProductos1.setModel(modelo);
        String[] dato = new String[9];
        for (int i = 0; i < ventas.size(); i++) {
            dato[0] = (ventas.get(i).getCodigo_Cliente());
            dato[1] = ventas.get(i).getNombre_Cliente();
             dato[2] = ventas.get(i).getDireccion_Cliente();
             dato[3] = (ventas.get(i).getTelefono_Cliente());
            dato[4] = ventas.get(i).getNit_Cliente();
            dato[5] = (ventas.get(i).getEmail_Cliente());
              dato[6] = (ventas.get(i).getSaldo_Cliente());
                dato[7] = (ventas.get(i).getCuenta_Cliente());
            dato[8] = (ventas.get(i).getEstatus_Cliente());
         

            System.out.println("vendedor:" + ventas);
            modelo.addRow(dato);
        }
    }

    public void buscarVendedor() {

        ClienteDao Clientes = new ClienteDao();

        Cliente Buscar = new Cliente() ;
        Buscar.setCodigo_Cliente(Txt_codigo.getText());
        Buscar = Clientes.query(Buscar);
        Txt_nombre.setText(Buscar.getNombre_Cliente());
        Txt_nit.setText(Buscar.getNit_Cliente());
         Txt_email.setText(Buscar.getEmail_Cliente());
        Txt_estatus.setText(Buscar.getEstatus_Cliente());
          Txt_saldo.setText(Buscar.getSaldo_Cliente());
            Txt_cuenta.setText(Buscar.getCuenta_Cliente());
        Txt_telefono.setText(Buscar.getTelefono_Cliente());
          Txt_direccion.setText(Buscar.getDireccion_Cliente());
   

    }

    public void limpiar() {
        Txt_codigo.setText("");
        Txt_nombre.setText("");
        Txt_nit.setText("");
        Txt_estatus.setText("");
        Txt_telefono.setText("");
        Txt_direccion.setText("");
        Txt_saldo.setText("");
        Txt_cuenta.setText("");
        Txt_email.setText("");
        
    
    }

    /**
     * Creates new form Mantenimiento_Cliente
     */
    public Mantenimiento_Cliente() {
        int codigoAplicacion = 3001;
        initComponents();
//        habilitarAcciones();
        llenadoDeTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        Btn_Modificar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Agregar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Txt_nombre = new javax.swing.JTextField();
        Txt_nit = new javax.swing.JTextField();
        Txt_telefono = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JtProductos1 = new javax.swing.JTable();
        Txt_estatus = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Btn_reporte = new javax.swing.JButton();
        Txt_cuenta = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Txt_email = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        Txt_saldo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Txt_direccion = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Btn_Buscar = new javax.swing.JButton();
        Txt_codigo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimieto Cliente\n");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Modificar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Modificar.setText("Modificar");
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 100, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Mantenimiento Cliente");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        Btn_Eliminar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 90, 30));

        Btn_Agregar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Agregar.setText("Guardar");
        Btn_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AgregarActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Agregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 100, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nit");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 201, -1, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Telefono");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 170, -1, -1));
        getContentPane().add(Txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, -1));

        Txt_nit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_nitActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_nit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 200, 180, -1));
        getContentPane().add(Txt_telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 180, -1));

        JtProductos1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        JtProductos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(JtProductos1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 330, 620, 138));

        Txt_estatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_estatusActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_estatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 180, 20));

        jButton1.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        jButton1.setText("Ayuda");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 7, 90, 30));

        Btn_reporte.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_reporte.setText("Reporte");
        Btn_reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_reporteActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_reporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 90, 30));

        Txt_cuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_cuentaActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_cuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 180, 20));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Email");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 10));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Saldo");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, -1, 10));

        Txt_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_emailActionPerformed(evt);
            }
        });
        getContentPane().add(Txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, 180, 20));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel11.setText("Cuenta");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, 10));
        getContentPane().add(Txt_saldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 120, 180, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(459, 167, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Direccion ");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 132, -1, -1));
        getContentPane().add(Txt_direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 180, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Buscar.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Btn_Buscar.setText("Buscar");
        Btn_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuscarActionPerformed(evt);
            }
        });
        jPanel2.add(Btn_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 90, 30));

        Txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_codigoActionPerformed(evt);
            }
        });
        jPanel2.add(Txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 180, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Cliente Nombre");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Estatus de Cliente");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, 10));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Codigo Cliente");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 620, 220));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed

        ClienteDao dao = new ClienteDao();

        Cliente modi = new Cliente();
        
         modi.setCodigo_Cliente(Txt_codigo.getText());
         modi.setNombre_Cliente(Txt_nombre.getText());
         modi.setNit_Cliente(Txt_nit.getText());
          modi.setDireccion_Cliente(Txt_direccion.getText());       
         modi.setEstatus_Cliente(Txt_estatus.getText());
         modi.setTelefono_Cliente(Txt_telefono.getText());
       modi.setSaldo_Cliente(Txt_saldo.getText());
         modi.setCuenta_Cliente(Txt_cuenta.getText());
          modi.setEmail_Cliente(Txt_email.getText());
        dao.update(modi);
        llenadoDeTablas();
        limpiar();
        BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();

        Insertar.setAccion("Modificar");
        Insertar.setId_Usuario(Login.usuarioComercial);
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();
        Insertar.setCodigoAplicacion("3001");
        Insertar.setModulo("3000");

        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
       



        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ModificarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
//
        ClienteDao acreedor = new ClienteDao();

        Cliente vendedorAEliminar = new Cliente();
            vendedorAEliminar.setCodigo_Cliente(Txt_codigo.getText());
         vendedorAEliminar.setNombre_Cliente(Txt_nombre.getText());
         vendedorAEliminar.setNit_Cliente(Txt_nit.getText());
          vendedorAEliminar.setDireccion_Cliente(Txt_direccion.getText());       
         vendedorAEliminar.setEstatus_Cliente(Txt_estatus.getText());
        vendedorAEliminar.setTelefono_Cliente(Txt_telefono.getText());
       vendedorAEliminar.setSaldo_Cliente(Txt_saldo.getText());
         vendedorAEliminar.setCuenta_Cliente(Txt_cuenta.getText());
          vendedorAEliminar.setEmail_Cliente(Txt_email.getText());
        acreedor.delete(vendedorAEliminar);
        llenadoDeTablas();
        limpiar();
        JOptionPane.showMessageDialog(null, "Cliente Eliminado.");
        BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();

        Insertar.setAccion("Eliminar");
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();
        Insertar.setCodigoAplicacion("3001");
        Insertar.setModulo("3000");
        Insertar.setId_Usuario(Login.usuarioComercial);
        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuscarActionPerformed
        buscarVendedor() ;
        BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();

        Insertar.setAccion("Buscar");
        GenerarPermisos permisos = new GenerarPermisos();
        MDI_Components mdi_Components = new MDI_Components();
        Insertar.setCodigoAplicacion("3001");
        Insertar.setModulo("3000");
        Insertar.setId_Usuario(Login.usuarioComercial);
        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }

//        buscarVendedor();
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BuscarActionPerformed

    private void Btn_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AgregarActionPerformed

////        GenerarPermisos permisos = new GenerarPermisos();
////        MDI_Components mdi_Components = new MDI_Components();
////
////        String id = "0";
        ClienteDao ClienteDAO = new ClienteDao();

        Cliente AInsertar = new Cliente();
        AInsertar.setCodigo_Cliente(Txt_codigo.getText());
        AInsertar.setNombre_Cliente(Txt_nombre.getText());
        AInsertar.setNit_Cliente(Txt_nit.getText());
         AInsertar.setDireccion_Cliente(Txt_direccion.getText());       
      
        AInsertar.setTelefono_Cliente(Txt_telefono.getText());
       AInsertar.setSaldo_Cliente(Txt_saldo.getText());
        AInsertar.setCuenta_Cliente(Txt_cuenta.getText());
         AInsertar.setEmail_Cliente(Txt_email.getText());
            AInsertar.setEstatus_Cliente(Txt_estatus.getText());
        ClienteDAO.insert(AInsertar);

        llenadoDeTablas();
        limpiar();
        BitacoraDao BitacoraDAO = new BitacoraDao();

        Bitacora Insertar = new Bitacora();
        Insertar.setId_Usuario(Login.usuarioComercial);
        Insertar.setAccion("Insertar");

        Insertar.setCodigoAplicacion("3001");
        Insertar.setModulo("3000");

        try {
            BitacoraDAO.insert(Insertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_AgregarActionPerformed

    private void Txt_nitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if ((new File("src\\main\\java\\Comercial\\reportes\\cliente.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\Comercial\\reportes\\cliente.chm");
                p.waitFor();
            } else {
                JOptionPane.showMessageDialog(null, "La ayuda no Fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Txt_estatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_estatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_estatusActionPerformed
private Connection connection = null;
    private void Btn_reporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_reporteActionPerformed
//  Map p = new HashMap();
//        JasperReport report;
//        JasperPrint print;
//
//        try {
//            connection = Conexion.getConnection();
//            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
//                    + "/src/main/java/Comercial/reportes/MantenimientoCliente.jrxml");
//            print = JasperFillManager.fillReport(report, p, connection);
//            JasperViewer view = new JasperViewer(print, false);
//            view.setTitle("cliente ");
//            view.setVisible(true);
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
        

        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_reporteActionPerformed

    private void Txt_cuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_cuentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_cuentaActionPerformed

    private void Txt_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_emailActionPerformed

    private void Txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_codigoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Agregar;
    private javax.swing.JButton Btn_Buscar;
    private javax.swing.JButton Btn_Eliminar;
    private javax.swing.JButton Btn_Modificar;
    private javax.swing.JButton Btn_reporte;
    private javax.swing.JTable JtProductos1;
    private javax.swing.JTextField Txt_codigo;
    private javax.swing.JTextField Txt_cuenta;
    private javax.swing.JTextField Txt_direccion;
    private javax.swing.JTextField Txt_email;
    private javax.swing.JTextField Txt_estatus;
    private javax.swing.JTextField Txt_nit;
    private javax.swing.JTextField Txt_nombre;
    private javax.swing.JTextField Txt_saldo;
    private javax.swing.JTextField Txt_telefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
