/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Comercial.vista;

import Comercial.datos.ProveedorDAO;
import Comercial.datos.Conexion;
import Comercial.dominio.Proveedor;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import Comercial.datos.Conexion;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author SipaqueRitaMaria
 */
public class Mantenimiento_Proveedor extends javax.swing.JInternalFrame {

    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("Nombre");
        modelo.addColumn("Dirección");
        modelo.addColumn("Telefono");
        modelo.addColumn("Nit");
        modelo.addColumn("Email");
        modelo.addColumn("Saldo");
        modelo.addColumn("Estado");
        ProveedorDAO proveedorDAO = new ProveedorDAO();

        List<Proveedor> proveedor = proveedorDAO.select();
        Tbl_Datos.setModel(modelo);
        String[] dato = new String[8];
        for (int i = 0; i < proveedor.size(); i++) {
            dato[0] = proveedor.get(i).getPK_codigo_Proveedor();
            dato[1] = proveedor.get(i).getNombre_Proveedor();
            dato[2] = proveedor.get(i).getDireccion_Proveedor();
            dato[3] = proveedor.get(i).getTelefono_Proveedor();
            dato[4] = proveedor.get(i).getNit_Proveedor();
            dato[5] = proveedor.get(i).getEmail_Proveedor();
            dato[6] = proveedor.get(i).getSaldo_Proveedor();
            dato[7] = proveedor.get(i).getEstatus_Proveedor();
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscar() {
        Proveedor proveedorAConsultar = new Proveedor();
        ProveedorDAO proveedorDAO = new ProveedorDAO();
        proveedorAConsultar.setPK_codigo_Proveedor(Txt_codigo.getText());
        proveedorAConsultar = proveedorDAO.query(proveedorAConsultar);

        Txt_nombre.setText(proveedorAConsultar.getNombre_Proveedor());
        Txt_direccion.setText(proveedorAConsultar.getDireccion_Proveedor());
        Txt_telefono.setText(proveedorAConsultar.getTelefono_Proveedor());
        Txt_nit.setText(proveedorAConsultar.getNit_Proveedor());
        Txt_email.setText(proveedorAConsultar.getEmail_Proveedor());
        Txt_saldo.setText(proveedorAConsultar.getSaldo_Proveedor());
        Txt_estado.setText(proveedorAConsultar.getEstatus_Proveedor());

    }

    public void limpiar() {
        Txt_codigo.setText("");
        Txt_nombre.setText("");
        Txt_direccion.setText("");
        Txt_telefono.setText("");
        Txt_nit.setText("");
        Txt_email.setText("");
        Txt_saldo.setText("");
        Txt_estado.setText("");

    }

    /**
     * Creates new form Mantenimiento_Proveedor
     */
    public Mantenimiento_Proveedor() {
        initComponents();
        llenadoDeTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_titulo = new javax.swing.JLabel();
        Btn_Ayuda = new javax.swing.JButton();
        Pnl_datos = new javax.swing.JPanel();
        Lbl_codigo = new javax.swing.JLabel();
        Txt_codigo = new javax.swing.JTextField();
        Lbl_nombre = new javax.swing.JLabel();
        Txt_nombre = new javax.swing.JTextField();
        Lbl_direccion = new javax.swing.JLabel();
        Txt_direccion = new javax.swing.JTextField();
        Lbl_estado = new javax.swing.JLabel();
        Lbl_saldo = new javax.swing.JLabel();
        Lbl_telefono = new javax.swing.JLabel();
        Lbl_nit = new javax.swing.JLabel();
        Lbl_email = new javax.swing.JLabel();
        Txt_saldo = new javax.swing.JTextField();
        Txt_telefono = new javax.swing.JTextField();
        Txt_nit = new javax.swing.JTextField();
        Txt_email = new javax.swing.JTextField();
        Txt_estado = new javax.swing.JTextField();
        Btn_Reporte = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Modificar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Reporte1 = new javax.swing.JButton();
        Pnl_detalle = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Datos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Mantenimiento Proveedor");
        setVisible(true);

        Lbl_titulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        Lbl_titulo.setText("Mantenimiento Proveedores");

        Btn_Ayuda.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Ayuda.setText("Ayuda");
        Btn_Ayuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_AyudaActionPerformed(evt);
            }
        });

        Pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Proveedores"));
        Pnl_datos.setForeground(new java.awt.Color(255, 255, 255));

        Lbl_codigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_codigo.setText("Codigo Proveedor:");

        Lbl_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre.setText("Nombre Proveedor:");

        Lbl_direccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion.setText("Direccion Proveedor:");

        Lbl_estado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_estado.setText("Estado Proveedor:");

        Lbl_saldo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_saldo.setText("Representante Proveedor:");

        Lbl_telefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_telefono.setText("Telefono Proveedor:");

        Lbl_nit.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nit.setText("Nit Proveedor:");

        Lbl_email.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_email.setText("Email Proveedor:");

        Btn_Reporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte.setText("Reporte");
        Btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReporteActionPerformed(evt);
            }
        });

        Btn_Guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Guardar.setText("Guardar");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_Modificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Modificar.setText("Modificar");
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_Reporte1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte1.setText("Buscar");
        Btn_Reporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pnl_datosLayout = new javax.swing.GroupLayout(Pnl_datos);
        Pnl_datos.setLayout(Pnl_datosLayout);
        Pnl_datosLayout.setHorizontalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_estado))
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(Lbl_telefono))
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_nit)
                            .addComponent(Lbl_email))
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datosLayout.createSequentialGroup()
                        .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)))
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(Btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Txt_estado, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                        .addComponent(Txt_saldo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Txt_email, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Txt_nit))))
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lbl_saldo)
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_nombre)
                            .addComponent(Lbl_codigo)
                            .addComponent(Lbl_direccion, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(34, 34, 34)
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                            .addComponent(Txt_nombre)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datosLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_direccion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_telefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(Btn_Reporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        Pnl_datosLayout.setVerticalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_codigo)
                    .addComponent(Txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte1))
                .addGap(7, 7, 7)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre)
                    .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_direccion)
                    .addComponent(Txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_telefono)
                    .addComponent(Txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_nit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_email, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_saldo)
                    .addComponent(Txt_saldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Lbl_estado))
                .addGap(25, 25, 25)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Pnl_detalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Proveedor"));

        Tbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tbl_Datos);

        javax.swing.GroupLayout Pnl_detalleLayout = new javax.swing.GroupLayout(Pnl_detalle);
        Pnl_detalle.setLayout(Pnl_detalleLayout);
        Pnl_detalleLayout.setHorizontalGroup(
            Pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        Pnl_detalleLayout.setVerticalGroup(
            Pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Pnl_detalle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lbl_titulo)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Ayuda, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(Pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_titulo)
                    .addComponent(Btn_Ayuda))
                .addGap(15, 15, 15)
                .addComponent(Pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pnl_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_AyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_AyudaActionPerformed

        try {
            if ((new File("src\\main\\java\\Comercial\\reportes\\AyuadaMantenimientoProveedor.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\Comercial\\reportes\\AyuadaMantenimientoProveedor.chm");
                p.waitFor();
            } else {
                JOptionPane.showMessageDialog(null, "La ayuda no Fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_Btn_AyudaActionPerformed
    private Connection connection = null;
    private void Btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReporteActionPerformed
        Map p = new HashMap();
        JasperReport report;
        JasperPrint print;

        try {
            connection = Conexion.getConnection();
            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
                    + "/src/main/java/Comercial/reportes/Aurorizacion.jrxml");
            print = JasperFillManager.fillReport(report, p, connection);
            JasperViewer view = new JasperViewer(print, false);
            view.setTitle("Reporte Mantenimiento Proveedor");
            view.setVisible(true);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_Btn_ReporteActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        // TODO add your handling code here:

        ProveedorDAO proveedorDAO = new ProveedorDAO();
        Proveedor proveedorAInsertar = new Proveedor();
        proveedorAInsertar.setPK_codigo_Proveedor(Txt_codigo.getText());
        proveedorAInsertar.setNombre_Proveedor(Txt_nombre.getText());
        proveedorAInsertar.setDireccion_Proveedor(Txt_direccion.getText());
        proveedorAInsertar.setTelefono_Proveedor(Txt_telefono.getText());
        proveedorAInsertar.setNit_Proveedor(Txt_nit.getText());
        proveedorAInsertar.setEmail_Proveedor(Txt_email.getText());
        proveedorAInsertar.setSaldo_Proveedor(Txt_saldo.getText());
        proveedorAInsertar.setEstatus_Proveedor(Txt_estado.getText());
        proveedorDAO.insert(proveedorAInsertar);

        llenadoDeTablas();
        limpiar();


    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed
        // TODO add your handling code here:
        ProveedorDAO proveedorDAO = new ProveedorDAO();
        Proveedor proveedorAActualizar = new Proveedor();
        proveedorAActualizar.setPK_codigo_Proveedor(Txt_codigo.getText());
        proveedorAActualizar.setNombre_Proveedor(Txt_nombre.getText());
        proveedorAActualizar.setDireccion_Proveedor(Txt_direccion.getText());
        proveedorAActualizar.setTelefono_Proveedor(Txt_telefono.getText());
        proveedorAActualizar.setNit_Proveedor(Txt_nit.getText());
        proveedorAActualizar.setEmail_Proveedor(Txt_email.getText());
        proveedorAActualizar.setSaldo_Proveedor(Txt_saldo.getText());
        proveedorAActualizar.setEstatus_Proveedor(Txt_estado.getText());

        proveedorDAO.update(proveedorAActualizar);
        JOptionPane.showMessageDialog(null, "Modificación Exitosa.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_ModificarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        // TODO add your handling code here:
        ProveedorDAO proveedorDAO = new ProveedorDAO();
        Proveedor proveedorAEliminar = new Proveedor();
        proveedorAEliminar.setPK_codigo_Proveedor(Txt_codigo.getText());
        proveedorDAO.delete(proveedorAEliminar);
        JOptionPane.showMessageDialog(null, "Registro Eliminado.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_Reporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte1ActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_Btn_Reporte1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Ayuda;
    public javax.swing.JButton Btn_Eliminar;
    public javax.swing.JButton Btn_Guardar;
    public javax.swing.JButton Btn_Modificar;
    public javax.swing.JButton Btn_Reporte;
    public javax.swing.JButton Btn_Reporte1;
    private javax.swing.JLabel Lbl_codigo;
    private javax.swing.JLabel Lbl_direccion;
    private javax.swing.JLabel Lbl_email;
    private javax.swing.JLabel Lbl_estado;
    private javax.swing.JLabel Lbl_nit;
    private javax.swing.JLabel Lbl_nombre;
    private javax.swing.JLabel Lbl_saldo;
    private javax.swing.JLabel Lbl_telefono;
    private javax.swing.JLabel Lbl_titulo;
    private javax.swing.JPanel Pnl_datos;
    private javax.swing.JPanel Pnl_detalle;
    private javax.swing.JTable Tbl_Datos;
    public javax.swing.JTextField Txt_codigo;
    public javax.swing.JTextField Txt_direccion;
    public javax.swing.JTextField Txt_email;
    public javax.swing.JTextField Txt_estado;
    public javax.swing.JTextField Txt_nit;
    public javax.swing.JTextField Txt_nombre;
    public javax.swing.JTextField Txt_saldo;
    public javax.swing.JTextField Txt_telefono;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

}
