package Comercial.vista;


import seguridad.vista.*;
//import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Dimension;
import java.io.File;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

import javax.swing.JOptionPane;
import javax.swing.UIManager;
import seguridad.datos.BitacoraDao;
import seguridad.dominio.Bitacora;

//import seguridad.datos.BitacoraDao;
//import seguridad.dominio.Bitacora;
/**
 *
 *
 */
public class MDIComercial extends javax.swing.JFrame {

    private Mantenimiento_Producto MantenimientoProducto;
    private Mantenimiento_Bodega Mantenimiento_Bodega;
    private Mantenimiento_Unidad MantenimientoUnidad;
    private Proceso_Factura_venta Proceso_Factura_venta;
    private Mantenimiento_Transporte MantenimientoTransporte;
    private Mantenimiento_Proveedor MantenimientoProveedor;
    private Mantenimiento_Marca MantenimientoMarca;
    private Mantenimiento_Linea MantenimientoLinea;
    private Mantenimiento_Cliente Mantenimiento_Cliente;
    private Mantenimiento_Cobrador Mantenimiento_Cobrador;
    private Mantenimiento_Vendedor Mantenimiento_Vendedor;
    private Proceso_Existencia Proceso_Existencia;
    private Mantenimiento_TransporteRuta Mantenimiento_TransporteRuta;
    private Proceso_Cartera_Venta Proceso_Cartera_Venta;
    private Proceso_Cotizacion_venta Proceso_Cotizacion_venta;
    private Proceso_Pedido_venta Proceso_Pedido_venta;
    private Proceso_Devolucion_venta Proceso_Devolucion_venta;
    private Control_Precios_vemta Control_Precios_vemta;
    private Balance_saldo_cliente registro_venta;
    private Proceso_Tipo_Documento Proceso_Tipo_Documento;
     private Porceso_FacturaCompras Proceso_FacturaCompra;
     private Proceso_AutorizacionOrdenCompra Proceso_AutorizacionOrdenCompra1;
    private BalanceSaldoProveedor BalanceSaldoProveedor;
    private Proceso_OrdenCompra Proceso_OrdenCompra;
    private ProcesoDevolucionCompra ProcesoDevolucionCompra;
    private ProcesoRecepcionCompra ProcesoRecepcionCompra;
    private AutorizacionOrdenCompra AutorizacionOrdenCompra;
    private MantenimientoFormaPago MantenimientoFormaPago;
    private ConsultasFacturas  ConsultasFacturas;
    private FmrBitacora FmrBitacora;
   
    
    public static JLabel logo = new JLabel();

    public MDIComercial() throws UnknownHostException {
        initComponents();
        logo(0);

//        GenerarPermisos permisos = new GenerarPermisos();
//        MDI_Components mdi_Components = new MDI_Components();
        String modulo_nombre = "Comercial";

//        this.setTitle("Usuario: " + "[" + Login.usuarioComercial + "]" + " \t" + "IP: [" + mdi_Components.getIp() + "]");
//        permisos.getPermisos(modulo_nombre, Login.usuarioComercial);
    }

    public void logo(int activar) {
        Icon icon = new ImageIcon("C:src/main/java/Imagen/2.jpg");
        logo.setSize(300, 300);
        if (icon != null) {
            //Agrega Icono
            logo.setIcon(icon);
        } else {
            //No existe imagen.
        }
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = logo.getSize();
        logo.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        logo.setVisible(true);
        jdpescritorio.add(logo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpescritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        M_ccompras = new javax.swing.JMenu();
        M_compras = new javax.swing.JMenu();
        Item_proveedor = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        M_inventario = new javax.swing.JMenu();
        Item_Mntbodega = new javax.swing.JCheckBoxMenuItem();
        Item_marca = new javax.swing.JCheckBoxMenuItem();
        Item_Linea = new javax.swing.JCheckBoxMenuItem();
        Item_Mntproducto = new javax.swing.JMenuItem();
        Item_Mntunidad = new javax.swing.JCheckBoxMenuItem();
        Item_Mnttransporte = new javax.swing.JCheckBoxMenuItem();
        MantenimientoRuta = new javax.swing.JCheckBoxMenuItem();
        M_venta = new javax.swing.JMenu();
        M_cliente = new javax.swing.JMenuItem();
        M_deudor = new javax.swing.JMenuItem();
        M_deudor1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        P_compras = new javax.swing.JMenu();
        ProcesoCompra = new javax.swing.JMenuItem();
        autorizacion = new javax.swing.JMenuItem();
        devolucion = new javax.swing.JMenuItem();
        recepcion = new javax.swing.JMenuItem();
        balance = new javax.swing.JMenuItem();
        auto = new javax.swing.JMenuItem();
        emi = new javax.swing.JMenuItem();
        P_producto = new javax.swing.JMenu();
        ProcesoExistencia = new javax.swing.JCheckBoxMenuItem();
        Item_Tipo_Documento = new javax.swing.JCheckBoxMenuItem();
        P_ventas = new javax.swing.JMenu();
        P_pedido_factura = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu12 = new javax.swing.JMenu();
        jMenu13 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu11 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        cerrar_sesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Hotelero");
        setResizable(false);

        jdpescritorio.setBackground(new java.awt.Color(0, 153, 153));

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));

        jMenu1.setText("Archivo");
        jMenu1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu1);

        M_ccompras.setText("Catalogos");
        M_ccompras.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        M_compras.setText("Mantenimientos Compras");

        Item_proveedor.setText("Mantenimiento Proveedor");
        Item_proveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_proveedorActionPerformed(evt);
            }
        });
        M_compras.add(Item_proveedor);

        jMenuItem9.setText("Mantenimiento Forma Pago");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        M_compras.add(jMenuItem9);

        M_ccompras.add(M_compras);

        M_inventario.setText("Mantenimientos Inventarios");

        Item_Mntbodega.setSelected(true);
        Item_Mntbodega.setText("Mantenimiento Bodegas");
        Item_Mntbodega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MntbodegaActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Mntbodega);

        Item_marca.setSelected(true);
        Item_marca.setText("Mantenimiento Marca");
        Item_marca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_marcaActionPerformed(evt);
            }
        });
        M_inventario.add(Item_marca);

        Item_Linea.setSelected(true);
        Item_Linea.setText("Mantenimiento Linea");
        Item_Linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_LineaActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Linea);

        Item_Mntproducto.setText("Mantenimiento Producto");
        Item_Mntproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MntproductoActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Mntproducto);

        Item_Mntunidad.setSelected(true);
        Item_Mntunidad.setText("Mantenimiento Unidad");
        Item_Mntunidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MntunidadActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Mntunidad);

        Item_Mnttransporte.setSelected(true);
        Item_Mnttransporte.setText("Mantenimiento Trasnporte");
        Item_Mnttransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_MnttransporteActionPerformed(evt);
            }
        });
        M_inventario.add(Item_Mnttransporte);

        MantenimientoRuta.setSelected(true);
        MantenimientoRuta.setText("Mantenimiento Ruta");
        MantenimientoRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MantenimientoRutaActionPerformed(evt);
            }
        });
        M_inventario.add(MantenimientoRuta);

        M_ccompras.add(M_inventario);

        M_venta.setText("Mantenimientos Ventas");

        M_cliente.setText("Mantenimineto Cliente");
        M_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_clienteActionPerformed(evt);
            }
        });
        M_venta.add(M_cliente);

        M_deudor.setText("Mantenimiento Cobradores");
        M_deudor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_deudorActionPerformed(evt);
            }
        });
        M_venta.add(M_deudor);

        M_deudor1.setText("Mantenimiento Vendedor");
        M_deudor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                M_deudor1ActionPerformed(evt);
            }
        });
        M_venta.add(M_deudor1);

        M_ccompras.add(M_venta);

        jMenuBar1.add(M_ccompras);

        jMenu4.setText("Procesos");
        jMenu4.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        P_compras.setText("ProcesoCompra");

        ProcesoCompra.setText("Orden de Compra");
        ProcesoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesoCompraActionPerformed(evt);
            }
        });
        P_compras.add(ProcesoCompra);

        autorizacion.setText("Factura Compras");
        autorizacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autorizacionActionPerformed(evt);
            }
        });
        P_compras.add(autorizacion);

        devolucion.setText("Devolucion Compra");
        devolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devolucionActionPerformed(evt);
            }
        });
        P_compras.add(devolucion);

        recepcion.setText("Recepcion Compras");
        recepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recepcionActionPerformed(evt);
            }
        });
        P_compras.add(recepcion);

        balance.setText("Balance de Saldos");
        balance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balanceActionPerformed(evt);
            }
        });
        P_compras.add(balance);

        auto.setText("Autorizacion Orden Compra");
        auto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoActionPerformed(evt);
            }
        });
        P_compras.add(auto);

        emi.setText("Consulras Facturas");
        emi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emiActionPerformed(evt);
            }
        });
        P_compras.add(emi);

        jMenu4.add(P_compras);

        P_producto.setText("Proceso Inventario");

        ProcesoExistencia.setSelected(true);
        ProcesoExistencia.setText("Proceso Existencia");
        ProcesoExistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProcesoExistenciaActionPerformed(evt);
            }
        });
        P_producto.add(ProcesoExistencia);

        Item_Tipo_Documento.setSelected(true);
        Item_Tipo_Documento.setText("Tipo Documento");
        Item_Tipo_Documento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Tipo_DocumentoActionPerformed(evt);
            }
        });
        P_producto.add(Item_Tipo_Documento);

        jMenu4.add(P_producto);

        P_ventas.setText("Proseso ventas");

        P_pedido_factura.setText(" Factura");
        P_pedido_factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P_pedido_facturaActionPerformed(evt);
            }
        });
        P_ventas.add(P_pedido_factura);

        jMenuItem2.setText("Cartera de Ventas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        P_ventas.add(jMenuItem2);

        jMenuItem3.setText("Pedido");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        P_ventas.add(jMenuItem3);

        jMenuItem4.setText("Cotizacion");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        P_ventas.add(jMenuItem4);

        jMenuItem5.setText("Devolucion de Venta");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        P_ventas.add(jMenuItem5);

        jMenuItem6.setText("Control de Precios");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        P_ventas.add(jMenuItem6);

        jMenuItem8.setText("Balance de Saldo a Cliente");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        P_ventas.add(jMenuItem8);

        jMenu4.add(P_ventas);

        jMenuBar1.add(jMenu4);

        jMenu12.setText("Informes");
        jMenu12.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jMenu13.setText("Historial");

        jMenuItem1.setText("Bitacora Comercial");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu13.add(jMenuItem1);

        jMenu12.add(jMenu13);

        jMenuBar1.add(jMenu12);

        jMenu6.setText("Herramientas");
        jMenu6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ayuda");
        jMenu7.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N

        jMenu11.setText("Ayuda");
        jMenu11.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N

        jMenuItem7.setText("Ayuda Menu");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu11.add(jMenuItem7);

        jMenu7.add(jMenu11);

        jMenuBar1.add(jMenu7);

        cerrar_sesion.setText("Cerrar Sesión");
        cerrar_sesion.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        cerrar_sesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrar_sesionMouseClicked(evt);
            }
        });
        jMenuBar1.add(cerrar_sesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpescritorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void emiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emiActionPerformed
ConsultasFacturas = new  ConsultasFacturas();

        jdpescritorio.add( ConsultasFacturas);

    }//GEN-LAST:event_emiActionPerformed

    private void Item_proveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_proveedorActionPerformed
// TODO add your handling code here:
        MantenimientoProveedor = new Mantenimiento_Proveedor();
        jdpescritorio.add(MantenimientoProveedor);

    }//GEN-LAST:event_Item_proveedorActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        
        FmrBitacora = new seguridad.vista.FmrBitacora();

        jdpescritorio.add(FmrBitacora);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = FmrBitacora.getSize();
        FmrBitacora.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        FmrBitacora.show();
        logo.setVisible(true);
        FmrBitacora.setVisible(true);

        Bitacora Bitacora = new Bitacora();

        Bitacora Insertar = new Bitacora();
        Insertar.setId_Usuario(Login.usuarioComercial);
        Insertar.setAccion("Accesso");

        Insertar.setCodigoAplicacion("200");
        Insertar.setModulo("3000");

     
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void cerrar_sesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrar_sesionMouseClicked
        int respuesta_cs = JOptionPane.showConfirmDialog(this, "¿Desea Cerrar Sesión?", "Cerrar Sesión", JOptionPane.YES_NO_OPTION);
        if (respuesta_cs == 0) {
            this.dispose();
        }

    }//GEN-LAST:event_cerrar_sesionMouseClicked

    private void Item_MntproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MntproductoActionPerformed
        MantenimientoProducto = new Mantenimiento_Producto();
        jdpescritorio.add(MantenimientoProducto);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoProducto.getSize();
        MantenimientoProducto.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoProducto.show();
        logo.setVisible(true);
        MantenimientoProducto.setVisible(true);

    }//GEN-LAST:event_Item_MntproductoActionPerformed

    private void autorizacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autorizacionActionPerformed
        // TODO add your handling code here:
        Proceso_FacturaCompra = new Porceso_FacturaCompras();

        jdpescritorio.add(Proceso_FacturaCompra);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_FacturaCompra.getSize();
      Proceso_FacturaCompra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
     Proceso_FacturaCompra.show();
        logo.setVisible(true);
       Proceso_FacturaCompra.setVisible(true);


    }//GEN-LAST:event_autorizacionActionPerformed

    private void ProcesoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesoCompraActionPerformed
Proceso_OrdenCompra = new Proceso_OrdenCompra();

        jdpescritorio.add(Proceso_OrdenCompra);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_OrdenCompra.getSize();
        Proceso_OrdenCompra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_OrdenCompra.show();
        logo.setVisible(true);
        Proceso_OrdenCompra.setVisible(true);        // TODO add your handling code here:

    }//GEN-LAST:event_ProcesoCompraActionPerformed

    private void Item_MntbodegaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MntbodegaActionPerformed
        Mantenimiento_Bodega = new Mantenimiento_Bodega();
        jdpescritorio.add(Mantenimiento_Bodega);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Mantenimiento_Bodega.getSize();
        Mantenimiento_Bodega.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Mantenimiento_Bodega.show();
        logo.setVisible(true);
        Mantenimiento_Bodega.setVisible(true);


    }//GEN-LAST:event_Item_MntbodegaActionPerformed

    private void Item_marcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_marcaActionPerformed
        // TODO add your handling code here:
        MantenimientoMarca = new Mantenimiento_Marca();
        jdpescritorio.add(MantenimientoMarca);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoMarca.getSize();
        MantenimientoMarca.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoMarca.show();
        logo.setVisible(true);
        MantenimientoMarca.setVisible(true);
    }//GEN-LAST:event_Item_marcaActionPerformed

    private void Item_LineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_LineaActionPerformed
        // TODO add your handling code here:
        MantenimientoLinea = new Mantenimiento_Linea();
        jdpescritorio.add(MantenimientoLinea);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoLinea.getSize();
        MantenimientoLinea.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoLinea.show();
        logo.setVisible(true);
        MantenimientoLinea.setVisible(true);

    }//GEN-LAST:event_Item_LineaActionPerformed

    private void M_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_clienteActionPerformed
        Mantenimiento_Cliente = new Mantenimiento_Cliente();
        jdpescritorio.add(Mantenimiento_Cliente);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Mantenimiento_Cliente.getSize();
        Mantenimiento_Cliente.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Mantenimiento_Cliente.show();
        logo.setVisible(true);
        Mantenimiento_Cliente.setVisible(true);
    }//GEN-LAST:event_M_clienteActionPerformed

    private void M_deudorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_deudorActionPerformed
        Mantenimiento_Cobrador = new Mantenimiento_Cobrador();
        jdpescritorio.add(Mantenimiento_Cobrador);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Mantenimiento_Cobrador.getSize();
        Mantenimiento_Cobrador.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Mantenimiento_Cobrador.show();
        logo.setVisible(true);
        Mantenimiento_Cobrador.setVisible(true);

    }//GEN-LAST:event_M_deudorActionPerformed

    private void M_deudor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_M_deudor1ActionPerformed
        Mantenimiento_Vendedor = new Mantenimiento_Vendedor();
        jdpescritorio.add(Mantenimiento_Vendedor);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Mantenimiento_Vendedor.getSize();
        Mantenimiento_Vendedor.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Mantenimiento_Vendedor.show();
        logo.setVisible(true);
        Mantenimiento_Vendedor.setVisible(true);


    }//GEN-LAST:event_M_deudor1ActionPerformed

    private void Item_MntunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MntunidadActionPerformed
        // TODO add your handling code here:
        MantenimientoUnidad = new Mantenimiento_Unidad();
        jdpescritorio.add(MantenimientoUnidad);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoUnidad.getSize();
        MantenimientoUnidad.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoUnidad.show();
        logo.setVisible(true);
        MantenimientoUnidad.setVisible(true);
    }//GEN-LAST:event_Item_MntunidadActionPerformed

    private void Item_MnttransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_MnttransporteActionPerformed
        // TODO add your handling code here:
        MantenimientoTransporte = new Mantenimiento_Transporte();
        jdpescritorio.add(MantenimientoTransporte);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoTransporte.getSize();
        MantenimientoTransporte.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoTransporte.show();
        logo.setVisible(true);
        MantenimientoTransporte.setVisible(true);

    }//GEN-LAST:event_Item_MnttransporteActionPerformed

    private void ProcesoExistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProcesoExistenciaActionPerformed
        // TODO add your handling code here:
        Proceso_Existencia = new Proceso_Existencia();
        jdpescritorio.add(Proceso_Existencia);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_Existencia.getSize();
        Proceso_Existencia.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_Existencia.show();
        logo.setVisible(true);
        Proceso_Existencia.setVisible(true);


    }//GEN-LAST:event_ProcesoExistenciaActionPerformed

    private void MantenimientoRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MantenimientoRutaActionPerformed
        // TODO add your handling code here:
        Mantenimiento_TransporteRuta = new Mantenimiento_TransporteRuta();
        jdpescritorio.add(Mantenimiento_TransporteRuta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Mantenimiento_TransporteRuta.getSize();
        Mantenimiento_TransporteRuta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Mantenimiento_TransporteRuta.show();
        logo.setVisible(true);
        Mantenimiento_TransporteRuta.setVisible(true);

    }//GEN-LAST:event_MantenimientoRutaActionPerformed

    private void P_pedido_facturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P_pedido_facturaActionPerformed
        Proceso_Factura_venta = new Proceso_Factura_venta();

        jdpescritorio.add(Proceso_Factura_venta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_Factura_venta.getSize();
        Proceso_Factura_venta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_Factura_venta.show();
        logo.setVisible(true);
        Proceso_Factura_venta.setVisible(true);
        //
        // TODO add your handling code here:
    }//GEN-LAST:event_P_pedido_facturaActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        Proceso_Cartera_Venta = new Proceso_Cartera_Venta();

        jdpescritorio.add(Proceso_Cartera_Venta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_Cartera_Venta.getSize();
        Proceso_Cartera_Venta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_Cartera_Venta.show();
        logo.setVisible(true);
        Proceso_Cartera_Venta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        Proceso_Pedido_venta = new Proceso_Pedido_venta();

        jdpescritorio.add(Proceso_Pedido_venta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_Pedido_venta.getSize();
        Proceso_Pedido_venta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_Pedido_venta.show();
        logo.setVisible(true);
        Proceso_Pedido_venta.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        Proceso_Cotizacion_venta = new Proceso_Cotizacion_venta();

        jdpescritorio.add(Proceso_Cotizacion_venta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_Cotizacion_venta.getSize();
        Proceso_Cotizacion_venta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_Cotizacion_venta.show();
        logo.setVisible(true);
        Proceso_Cotizacion_venta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        Proceso_Devolucion_venta = new Proceso_Devolucion_venta();

        jdpescritorio.add(Proceso_Devolucion_venta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_Devolucion_venta.getSize();
        Proceso_Devolucion_venta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_Devolucion_venta.show();
        logo.setVisible(true);
        Proceso_Devolucion_venta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed

        Control_Precios_vemta = new Control_Precios_vemta();

        jdpescritorio.add(Control_Precios_vemta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Control_Precios_vemta.getSize();
        Control_Precios_vemta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Control_Precios_vemta.show();
        logo.setVisible(true);
        Control_Precios_vemta.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        Balance_saldo_cliente registro_venta = new Balance_saldo_cliente();

        jdpescritorio.add(registro_venta);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = registro_venta.getSize();
        registro_venta.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        registro_venta.show();
        logo.setVisible(true);
        registro_venta.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void Item_Tipo_DocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Tipo_DocumentoActionPerformed
        // TODO add your handling code here:
        Proceso_Tipo_Documento = new Proceso_Tipo_Documento();
        jdpescritorio.add(Proceso_Tipo_Documento);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_Tipo_Documento.getSize();
        Proceso_Tipo_Documento.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_Tipo_Documento.show();
        logo.setVisible(true);
        Proceso_Tipo_Documento.setVisible(true);
    }//GEN-LAST:event_Item_Tipo_DocumentoActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        MantenimientoFormaPago= new MantenimientoFormaPago();
        jdpescritorio.add(MantenimientoFormaPago);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = MantenimientoFormaPago.getSize();
        MantenimientoFormaPago.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        MantenimientoFormaPago.show();
        logo.setVisible(true);
        MantenimientoFormaPago.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void balanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balanceActionPerformed
        // TODO add your handling code here:
BalanceSaldoProveedor BalanceSaldoProveedor;
BalanceSaldoProveedor = new BalanceSaldoProveedor();
        
        jdpescritorio.add(BalanceSaldoProveedor);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = BalanceSaldoProveedor.getSize();
       BalanceSaldoProveedor.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        BalanceSaldoProveedor.show();
        logo.setVisible(true);
         BalanceSaldoProveedor.setVisible(true);       
    }//GEN-LAST:event_balanceActionPerformed

    private void devolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devolucionActionPerformed
        // TODO add your handling code here:
        

ProcesoDevolucionCompra ProcesoDevolucionCompra;
ProcesoDevolucionCompra = new ProcesoDevolucionCompra();

        


        jdpescritorio.add(ProcesoDevolucionCompra);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = ProcesoDevolucionCompra.getSize();
      ProcesoDevolucionCompra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
       ProcesoDevolucionCompra.show();
        logo.setVisible(true);
         ProcesoDevolucionCompra.setVisible(true);
                                           
    }//GEN-LAST:event_devolucionActionPerformed

    private void recepcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recepcionActionPerformed
        // TODO add your handling code here:
      ProcesoRecepcionCompra = new ProcesoRecepcionCompra();

        jdpescritorio.add(ProcesoRecepcionCompra);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = ProcesoRecepcionCompra.getSize();
        ProcesoRecepcionCompra.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        ProcesoRecepcionCompra.show();
        logo.setVisible(true);
        ProcesoRecepcionCompra.setVisible(true);
    }//GEN-LAST:event_recepcionActionPerformed

    private void autoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoActionPerformed
        // TODO add your handling code here:
        Proceso_AutorizacionOrdenCompra1 = new Proceso_AutorizacionOrdenCompra();

        jdpescritorio.add(Proceso_AutorizacionOrdenCompra1);
        Dimension desktopSize = jdpescritorio.getSize();
        Dimension FrameSize = Proceso_AutorizacionOrdenCompra1.getSize();
        Proceso_AutorizacionOrdenCompra1.setLocation((desktopSize.width - FrameSize.width) / 2, (desktopSize.height - FrameSize.height) / 2);
        Proceso_AutorizacionOrdenCompra1.show();
        logo.setVisible(true);
        Proceso_AutorizacionOrdenCompra1.setVisible(true);
    }//GEN-LAST:event_autoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
//            UIManager.setLookAndFeel(new FlatDarkLaf());
        } catch (Exception ex) {
            System.out.println(ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MDIComercial().setVisible(true);
                } catch (UnknownHostException ex) {
                    Logger.getLogger(MDIComercial.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem Item_Linea;
    private javax.swing.JCheckBoxMenuItem Item_Mntbodega;
    public static javax.swing.JMenuItem Item_Mntproducto;
    private javax.swing.JCheckBoxMenuItem Item_Mnttransporte;
    private javax.swing.JCheckBoxMenuItem Item_Mntunidad;
    private javax.swing.JCheckBoxMenuItem Item_Tipo_Documento;
    private javax.swing.JCheckBoxMenuItem Item_marca;
    public static javax.swing.JMenuItem Item_proveedor;
    public static javax.swing.JMenu M_ccompras;
    public static javax.swing.JMenuItem M_cliente;
    public static javax.swing.JMenu M_compras;
    public static javax.swing.JMenuItem M_deudor;
    public static javax.swing.JMenuItem M_deudor1;
    public static javax.swing.JMenu M_inventario;
    public static javax.swing.JMenu M_venta;
    private javax.swing.JCheckBoxMenuItem MantenimientoRuta;
    public static javax.swing.JMenu P_compras;
    public static javax.swing.JMenuItem P_pedido_factura;
    public static javax.swing.JMenu P_producto;
    public static javax.swing.JMenu P_ventas;
    public static javax.swing.JMenuItem ProcesoCompra;
    private javax.swing.JCheckBoxMenuItem ProcesoExistencia;
    private javax.swing.JMenuItem auto;
    public static javax.swing.JMenuItem autorizacion;
    private javax.swing.JMenuItem balance;
    public static javax.swing.JMenu cerrar_sesion;
    private javax.swing.JMenuItem devolucion;
    private javax.swing.JMenuItem emi;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu12;
    private javax.swing.JMenu jMenu13;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    public static javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    public static javax.swing.JDesktopPane jdpescritorio;
    private javax.swing.JMenuItem recepcion;
    // End of variables declaration//GEN-END:variables
}
