/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Comercial.vista;
import Comercial.datos.AutorizacionOrdenCompraDAO;
import Comercial.datos.Conexion;
import Comercial.dominio.AutorizacionOrdenCompra1;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.ButtonGroup;
import Comercial.datos.Conexion;
import Comercial.datos.Conexion;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import java.util.Map;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author SipaqueRitaMaria
 */
public class Proceso_AutorizacionOrdenCompra extends javax.swing.JInternalFrame {

    /**
     * Creates new form Proceso_AutorizacionOrdenCompra
     */
    public void llenadoDeTablas() {
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Codigo");
        modelo.addColumn("CodigoOrdenCompra");
        modelo.addColumn("Nombre");
        modelo.addColumn("Puesto");
        modelo.addColumn("Fecha");
        modelo.addColumn("Estado");
        
        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();
        List<AutorizacionOrdenCompra1> proveedor = proveedorDAO.select();
        Tbl_Datos.setModel(modelo);
        String[] dato = new String[6];
        for (int i = 0; i < proveedor.size(); i++) {
            dato[0] = Integer.toString(proveedor.get(i).getPK_codigo_autorizacion());
            dato[1] = proveedor.get(i).getCodigo_ordencompra();
            dato[2] = proveedor.get(i).getNombre_autorizacion();
            dato[3] = proveedor.get(i).getDepartamento_autorizacion();
            dato[4] = proveedor.get(i).getFecha_autorizacion();
            dato[5] = proveedor.get(i).getEstatus_autorizacion();
            //System.out.println("vendedor:" + vendedores);
            modelo.addRow(dato);
        }
    }

    public void buscar() {
        AutorizacionOrdenCompra1 proveedorAConsultar = new AutorizacionOrdenCompra1();
        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();
        proveedorAConsultar.setPK_codigo_autorizacion(Integer.parseInt(Txt_codigo.getText()));
        proveedorAConsultar = proveedorDAO.query(proveedorAConsultar);

        Txt_codigo_orden.setText(proveedorAConsultar.getCodigo_ordencompra());
        Txt_nombre.setText(proveedorAConsultar.getNombre_autorizacion());
        txt_puesto.setSelectedItem(proveedorAConsultar.getDepartamento_autorizacion());
        Txt_fecha.setText(proveedorAConsultar.getFecha_autorizacion());
        Txt_estado.setText(proveedorAConsultar.getEstatus_autorizacion());

    }

    public void limpiar() {
        Txt_codigo.setText("");
        Txt_codigo_orden.setText("");
        Txt_nombre.setText("");
      
       txt_puesto.setSelectedItem(null);
     Txt_fecha.setText("");  
      Txt_estado.setText("");

    }
    
    public Proceso_AutorizacionOrdenCompra() {
        initComponents();
        llenadoDeTablas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lbl_titulo = new javax.swing.JLabel();
        Pnl_datos = new javax.swing.JPanel();
        Lbl_codigo = new javax.swing.JLabel();
        Txt_codigo = new javax.swing.JTextField();
        Lbl_nombre = new javax.swing.JLabel();
        Txt_nombre = new javax.swing.JTextField();
        Lbl_direccion = new javax.swing.JLabel();
        Lbl_estado = new javax.swing.JLabel();
        Lbl_telefono = new javax.swing.JLabel();
        Txt_fecha = new javax.swing.JTextField();
        Txt_estado = new javax.swing.JTextField();
        Btn_Reporte = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_Modificar = new javax.swing.JButton();
        Btn_Eliminar = new javax.swing.JButton();
        Btn_Reporte1 = new javax.swing.JButton();
        txt_puesto = new javax.swing.JComboBox<>();
        Lbl_nombre1 = new javax.swing.JLabel();
        Txt_codigo_orden = new javax.swing.JTextField();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        Lbl_titulo1 = new javax.swing.JLabel();
        Pnl_datos1 = new javax.swing.JPanel();
        Lbl_codigo1 = new javax.swing.JLabel();
        Txt_codigo1 = new javax.swing.JTextField();
        Lbl_nombre2 = new javax.swing.JLabel();
        Txt_nombre1 = new javax.swing.JTextField();
        Lbl_direccion1 = new javax.swing.JLabel();
        Lbl_estado1 = new javax.swing.JLabel();
        Lbl_telefono1 = new javax.swing.JLabel();
        Txt_fecha1 = new javax.swing.JTextField();
        Txt_estado1 = new javax.swing.JTextField();
        Btn_Reporte2 = new javax.swing.JButton();
        Btn_Guardar1 = new javax.swing.JButton();
        Btn_Modificar1 = new javax.swing.JButton();
        Btn_Eliminar1 = new javax.swing.JButton();
        Btn_Reporte3 = new javax.swing.JButton();
        txt_puesto1 = new javax.swing.JComboBox<>();
        Lbl_nombre3 = new javax.swing.JLabel();
        Txt_codigo_proveedor1 = new javax.swing.JTextField();
        Pnl_detalle = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tbl_Datos = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        Lbl_titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lbl_titulo.setText("Proceso Autorizacion de Orden Compra");

        Pnl_datos.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_datos.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Autorizacion"));

        Lbl_codigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_codigo.setText("Codigo Autorizacion:");

        Lbl_nombre.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre.setText("Nombre Autorizante:");

        Lbl_direccion.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion.setText("Puesto Autorizante");

        Lbl_estado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_estado.setText("Estado Autorizacion:");

        Lbl_telefono.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_telefono.setText("Fecha Autorizacion");

        Btn_Reporte.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte.setText("Reporte");
        Btn_Reporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ReporteActionPerformed(evt);
            }
        });

        Btn_Guardar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Guardar.setText("Guardar");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_Modificar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Modificar.setText("Modificar");
        Btn_Modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ModificarActionPerformed(evt);
            }
        });

        Btn_Eliminar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Eliminar.setText("Eliminar");
        Btn_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_EliminarActionPerformed(evt);
            }
        });

        Btn_Reporte1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte1.setText("Buscar");
        Btn_Reporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte1ActionPerformed(evt);
            }
        });

        txt_puesto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente Administrativo", "Gerente general ", "Gerente de compras", "Jefe del departamento de compras", " " }));

        Lbl_nombre1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre1.setText("Codigo Orden Compra :");

        javax.swing.GroupLayout Pnl_datosLayout = new javax.swing.GroupLayout(Pnl_datos);
        Pnl_datos.setLayout(Pnl_datosLayout);
        Pnl_datosLayout.setHorizontalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_estado)
                            .addComponent(Lbl_telefono))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Pnl_datosLayout.createSequentialGroup()
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_codigo)
                                .addGroup(Pnl_datosLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Lbl_direccion))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datosLayout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lbl_nombre)))
                            .addComponent(Lbl_nombre1))
                        .addGap(32, 32, 32)
                        .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_codigo_orden, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Pnl_datosLayout.createSequentialGroup()
                                .addComponent(Txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Reporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        Pnl_datosLayout.setVerticalGroup(
            Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datosLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_codigo)
                    .addComponent(Txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre1)
                    .addComponent(Txt_codigo_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_nombre)
                    .addComponent(Txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_direccion)
                    .addComponent(txt_puesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_telefono)
                    .addComponent(Txt_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_estado)
                    .addComponent(Txt_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Pnl_datosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        jInternalFrame1.setClosable(true);
        jInternalFrame1.setIconifiable(true);
        jInternalFrame1.setMaximizable(true);
        jInternalFrame1.setResizable(true);

        Lbl_titulo1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        Lbl_titulo1.setText("Proceso Autorizacion de Orden Compra");

        Pnl_datos1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos Autorizacion"));

        Lbl_codigo1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_codigo1.setText("Codigo Autorizacion:");

        Lbl_nombre2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre2.setText("Nombre Autorizante:");

        Lbl_direccion1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_direccion1.setText("Puesto Autorizante");

        Lbl_estado1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_estado1.setText("Estado Autorizacion:");

        Lbl_telefono1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_telefono1.setText("Fecha Autorizacion");

        Btn_Reporte2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte2.setText("Reporte");
        Btn_Reporte2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte2ActionPerformed(evt);
            }
        });

        Btn_Guardar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Guardar1.setText("Guardar");
        Btn_Guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Guardar1ActionPerformed(evt);
            }
        });

        Btn_Modificar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Modificar1.setText("Modificar");
        Btn_Modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Modificar1ActionPerformed(evt);
            }
        });

        Btn_Eliminar1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Eliminar1.setText("Eliminar");
        Btn_Eliminar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Eliminar1ActionPerformed(evt);
            }
        });

        Btn_Reporte3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Btn_Reporte3.setText("Buscar");
        Btn_Reporte3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Reporte3ActionPerformed(evt);
            }
        });

        txt_puesto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gerente Administrativo", "Gerente general ", "Gerente de compras", "Jefe del departamento de compras", " " }));

        Lbl_nombre3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        Lbl_nombre3.setText("Codigo Orden Compra :");

        javax.swing.GroupLayout Pnl_datos1Layout = new javax.swing.GroupLayout(Pnl_datos1);
        Pnl_datos1.setLayout(Pnl_datos1Layout);
        Pnl_datos1Layout.setHorizontalGroup(
            Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos1Layout.createSequentialGroup()
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pnl_datos1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Btn_Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_Eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Reporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pnl_datos1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Lbl_estado1)
                            .addComponent(Lbl_telefono1))
                        .addGap(18, 18, 18)
                        .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Txt_estado1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Pnl_datos1Layout.createSequentialGroup()
                        .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(Lbl_codigo1)
                                .addGroup(Pnl_datos1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(Lbl_direccion1))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pnl_datos1Layout.createSequentialGroup()
                                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Lbl_nombre2)))
                            .addComponent(Lbl_nombre3))
                        .addGap(32, 32, 32)
                        .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Txt_codigo_proveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_puesto1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Pnl_datos1Layout.createSequentialGroup()
                                .addComponent(Txt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Btn_Reporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        Pnl_datos1Layout.setVerticalGroup(
            Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_datos1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_codigo1)
                    .addComponent(Txt_codigo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_nombre3)
                    .addComponent(Txt_codigo_proveedor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_nombre2)
                    .addComponent(Txt_nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Lbl_direccion1)
                    .addComponent(txt_puesto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_telefono1)
                    .addComponent(Txt_fecha1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lbl_estado1)
                    .addComponent(Txt_estado1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(Pnl_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Guardar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Modificar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Eliminar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Reporte2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Lbl_titulo1)
                .addGap(133, 133, 133))
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pnl_datos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_titulo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pnl_datos1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Pnl_detalle.setBackground(new java.awt.Color(255, 255, 255));
        Pnl_detalle.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle Autorizacion"));

        Tbl_Datos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(Tbl_Datos);

        javax.swing.GroupLayout Pnl_detalleLayout = new javax.swing.GroupLayout(Pnl_detalle);
        Pnl_detalle.setLayout(Pnl_detalleLayout);
        Pnl_detalleLayout.setHorizontalGroup(
            Pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        Pnl_detalleLayout.setVerticalGroup(
            Pnl_detalleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pnl_detalleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Lbl_titulo)
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Pnl_detalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Pnl_datos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 19, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 287, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 287, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lbl_titulo)
                .addGap(23, 23, 23)
                .addComponent(Pnl_datos, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pnl_detalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 278, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 279, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_ReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ReporteActionPerformed
//        Map p = new HashMap();
//        JasperReport report;
//        JasperPrint print;
//
//        try {
//            connection = Conexion.getConnection();
//            report = JasperCompileManager.compileReport(new File("").getAbsolutePath()
//                + "/src/main/java/Comercial/reportes/Proveedor.jrxml");
//            print = JasperFillManager.fillReport(report, p, connection);
//            JasperViewer view = new JasperViewer(print, false);
//            view.setTitle("Reporte Mantenimiento Proveedor");
//            view.setVisible(true);
//
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
    }//GEN-LAST:event_Btn_ReporteActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        // TODO add your handling code here:

        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();
        AutorizacionOrdenCompra1 insertar = new AutorizacionOrdenCompra1();
        insertar.setPK_codigo_autorizacion((int) Integer.parseInt(Txt_codigo.getText()));
        insertar.setCodigo_ordencompra(Txt_codigo_orden.getText());
        insertar.setNombre_autorizacion(Txt_nombre.getText());
        insertar.setDepartamento_autorizacion(txt_puesto.getSelectedItem().toString());
        insertar.setFecha_autorizacion(Txt_fecha.getText());
        insertar.setEstatus_autorizacion(Txt_estado.getText());
        proveedorDAO.insert(insertar);

        llenadoDeTablas();
        limpiar();

    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_ModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ModificarActionPerformed
        // TODO add your handling code here:
        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();
        AutorizacionOrdenCompra1 proveedorAActualizar = new AutorizacionOrdenCompra1();
        proveedorAActualizar.setPK_codigo_autorizacion(Integer.parseInt(Txt_codigo.getText()));
        proveedorAActualizar.setCodigo_ordencompra(Txt_codigo_orden.getText());
        proveedorAActualizar.setNombre_autorizacion(Txt_nombre.getText());
        proveedorAActualizar.setDepartamento_autorizacion(txt_puesto.getSelectedItem().toString());
        proveedorAActualizar.setFecha_autorizacion(Txt_fecha.getText());
        proveedorAActualizar.setEstatus_autorizacion(Txt_estado.getText());

        proveedorDAO.update(proveedorAActualizar);
        JOptionPane.showMessageDialog(null, "Modificación Exitosa.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_ModificarActionPerformed

    private void Btn_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_EliminarActionPerformed
        // TODO add your handling code here:
        AutorizacionOrdenCompraDAO proveedorDAO = new AutorizacionOrdenCompraDAO();
        AutorizacionOrdenCompra1 proveedorAEliminar = new AutorizacionOrdenCompra1();
        proveedorAEliminar.setPK_codigo_autorizacion(Integer.parseInt(Txt_codigo.getText()));
        proveedorDAO.delete(proveedorAEliminar);
       
        JOptionPane.showMessageDialog(null, "Registro Eliminado.");
        llenadoDeTablas();
        limpiar();
    }//GEN-LAST:event_Btn_EliminarActionPerformed

    private void Btn_Reporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte1ActionPerformed
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_Btn_Reporte1ActionPerformed

    private void Txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_nombreActionPerformed

    private void Btn_Reporte2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Reporte2ActionPerformed

    private void Btn_Guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Guardar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Guardar1ActionPerformed

    private void Btn_Modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Modificar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Modificar1ActionPerformed

    private void Btn_Eliminar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Eliminar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Eliminar1ActionPerformed

    private void Btn_Reporte3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Reporte3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_Reporte3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton Btn_Eliminar;
    public javax.swing.JButton Btn_Eliminar1;
    public javax.swing.JButton Btn_Guardar;
    public javax.swing.JButton Btn_Guardar1;
    public javax.swing.JButton Btn_Modificar;
    public javax.swing.JButton Btn_Modificar1;
    public javax.swing.JButton Btn_Reporte;
    public javax.swing.JButton Btn_Reporte1;
    public javax.swing.JButton Btn_Reporte2;
    public javax.swing.JButton Btn_Reporte3;
    private javax.swing.JLabel Lbl_codigo;
    private javax.swing.JLabel Lbl_codigo1;
    private javax.swing.JLabel Lbl_direccion;
    private javax.swing.JLabel Lbl_direccion1;
    private javax.swing.JLabel Lbl_estado;
    private javax.swing.JLabel Lbl_estado1;
    private javax.swing.JLabel Lbl_nombre;
    private javax.swing.JLabel Lbl_nombre1;
    private javax.swing.JLabel Lbl_nombre2;
    private javax.swing.JLabel Lbl_nombre3;
    private javax.swing.JLabel Lbl_telefono;
    private javax.swing.JLabel Lbl_telefono1;
    private javax.swing.JLabel Lbl_titulo;
    private javax.swing.JLabel Lbl_titulo1;
    private javax.swing.JPanel Pnl_datos;
    private javax.swing.JPanel Pnl_datos1;
    private javax.swing.JPanel Pnl_detalle;
    private javax.swing.JTable Tbl_Datos;
    public javax.swing.JTextField Txt_codigo;
    public javax.swing.JTextField Txt_codigo1;
    public javax.swing.JTextField Txt_codigo_orden;
    public javax.swing.JTextField Txt_codigo_proveedor1;
    public javax.swing.JTextField Txt_estado;
    public javax.swing.JTextField Txt_estado1;
    public javax.swing.JTextField Txt_fecha;
    public javax.swing.JTextField Txt_fecha1;
    public javax.swing.JTextField Txt_nombre;
    public javax.swing.JTextField Txt_nombre1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox<String> txt_puesto;
    private javax.swing.JComboBox<String> txt_puesto1;
    // End of variables declaration//GEN-END:variables
}
