/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package seguridad.vista;
import java.io.File;
import java.net.UnknownHostException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import seguridad.datos.BitacoraDao;
import seguridad.dominio.Modulos;
import seguridad.datos.ModulosDAO;
import seguridad.dominio.Bitacora;

/**
 * /**
 *
 * @author Herbert Leonel Dominguez Chavez 15/02/2021
 */
public class Mantenimiento_Modulos extends javax.swing.JInternalFrame {
    DefaultTableModel modelo1; 
    String codigoAplicacion = "40";
    /**
     * Creates new form Mantenimiento_Modulos
     */
    public Mantenimiento_Modulos() {
        initComponents();
        limpio.setVisible(false);
        actualizartabla();
            
    }
    public void actualizartabla(){
        modelo1=new DefaultTableModel();   //ASIGNAMOS UN NUEVO DEFAULTABLEMODEL AL OBJETO MODELO1
        modelo1.addColumn("CODIGO");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("NOMBRE");
        modelo1.addColumn("DESCRIPCION");      //LE AÑADIMOS COLUMNAS AL OBJETO MODELO
        modelo1.addColumn("ESTADO");
        tabla1.setModel(modelo1);
        String datos[]= new String[4];
        ModulosDAO dao = new  ModulosDAO();
        List<Modulos> Modulo = dao.select();
        for (Modulos persona : Modulo) {       
               datos[0]=String.valueOf(persona.getCodigo_modulo());
               datos[1]=persona.getNombre_modulo();
               datos[2]=persona.getDescripcion_modulo();
               datos[3]=persona.getEstado_modulo();  
               modelo1.addRow(datos);
               tabla1.setModel(modelo1);
               }
    }
    public void limpiar(){
        txt_Codigo_Modulo.setText("");
        txt_Nombre_Modulo.setText("");
        txt_Descripcion_Modulo.setText("");
        limpio.setSelected(true);
    }
    private static boolean isNumeric(String cadena){
        try {
                Integer.parseInt(cadena);
                return true;
        } catch (NumberFormatException nfe){
                return false;
        }
    }
    private void GuardarEnBitacora(String accion, String codigoModulo, String idUsuario){
        BitacoraDao BitacoraDAO = new BitacoraDao();
        Bitacora AInsertar = new Bitacora();
        boolean estado=false;
        switch(accion){
            case "Insertar":
                AInsertar.setId_Usuario(idUsuario);
                AInsertar.setAccion("Inserción");
                AInsertar.setCodigoAplicacion(codigoModulo);estado=true;
                break;
            case "Modificacion":
                AInsertar.setId_Usuario(idUsuario);
                AInsertar.setAccion("Modificación");
                AInsertar.setCodigoAplicacion(codigoModulo);estado=true;
                break;
            case "Eliminacion":
                AInsertar.setId_Usuario(idUsuario);
                AInsertar.setAccion("Eliminar");
                AInsertar.setCodigoAplicacion(codigoModulo);estado=true;
        }
        if (estado==true) {
        try {
            BitacoraDAO.insert(AInsertar);
        } catch (UnknownHostException ex) {
            Logger.getLogger(Aplicacion_Perfil.class.getName()).log(Level.SEVERE, null, ex);
        }
        }         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ESTADO = new javax.swing.ButtonGroup();
        CajaInformacion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt_Codigo_Modulo = new javax.swing.JTextField();
        txt_Nombre_Modulo = new javax.swing.JTextField();
        BtnBus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_Descripcion_Modulo = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        activo = new javax.swing.JRadioButton();
        inactivo = new javax.swing.JRadioButton();
        limpio = new javax.swing.JRadioButton();
        BtnIng = new javax.swing.JButton();
        BtnMod = new javax.swing.JButton();
        BtnElim = new javax.swing.JButton();
        btn_limpiar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla1 = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("MANTENIMIENTO DE MODULOS");
        setEnabled(false);
        setPreferredSize(new java.awt.Dimension(790, 645));
        setVisible(true);

        CajaInformacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Información:"));
        CajaInformacion.setAutoscrolls(true);

        jLabel1.setText("CODIGO:");

        jLabel2.setText("NOMBRE:");

        jLabel3.setText("DESCRIPCIÓN:");

        BtnBus.setText("BUSCAR");
        BtnBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBusActionPerformed(evt);
            }
        });

        txt_Descripcion_Modulo.setColumns(20);
        txt_Descripcion_Modulo.setRows(5);
        jScrollPane1.setViewportView(txt_Descripcion_Modulo);

        jLabel4.setText("ESTADO:");

        ESTADO.add(activo);
        activo.setText("ACTIVO");

        ESTADO.add(inactivo);
        inactivo.setText("INACTIVO");

        ESTADO.add(limpio);
        limpio.setEnabled(false);

        BtnIng.setText("GUARDAR");
        BtnIng.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngActionPerformed(evt);
            }
        });

        BtnMod.setText("MODIFICAR");
        BtnMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnModActionPerformed(evt);
            }
        });

        BtnElim.setText("ELIMINAR");
        BtnElim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnElimActionPerformed(evt);
            }
        });

        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        jButton2.setText("AYUDA");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CajaInformacionLayout = new javax.swing.GroupLayout(CajaInformacion);
        CajaInformacion.setLayout(CajaInformacionLayout);
        CajaInformacionLayout.setHorizontalGroup(
            CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CajaInformacionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CajaInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_Codigo_Modulo))
                    .addGroup(CajaInformacionLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(9, 9, 9)
                        .addComponent(txt_Nombre_Modulo))
                    .addGroup(CajaInformacionLayout.createSequentialGroup()
                        .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CajaInformacionLayout.createSequentialGroup()
                                .addComponent(activo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inactivo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(limpio))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtnIng, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnBus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnMod, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnElim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
        );
        CajaInformacionLayout.setVerticalGroup(
            CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CajaInformacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Codigo_Modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_Nombre_Modulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(CajaInformacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activo)
                    .addComponent(inactivo)
                    .addComponent(limpio)
                    .addComponent(jLabel4))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(CajaInformacionLayout.createSequentialGroup()
                .addComponent(BtnBus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnIng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnMod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnElim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_limpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tabla1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla1.setEnabled(false);
        jScrollPane2.setViewportView(tabla1);
        tabla1.getAccessibleContext().setAccessibleParent(jScrollPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CajaInformacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CajaInformacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBusActionPerformed
        if (Mantenimiento_Modulos.isNumeric(txt_Codigo_Modulo.getText())&&txt_Codigo_Modulo.getText().length()!=0) {
            
    ModulosDAO moduloDAO = new ModulosDAO();
    Modulos moduloConsultar = new Modulos();
    moduloConsultar.setCodigo_modulo(Integer.parseInt(txt_Codigo_Modulo.getText()));
    moduloConsultar = moduloDAO.query(moduloConsultar);
                
    txt_Nombre_Modulo.setText(moduloConsultar.getNombre_modulo());
    txt_Descripcion_Modulo.setText(moduloConsultar.getDescripcion_modulo());
        if (Integer.parseInt(moduloConsultar.getEstado_modulo())==1) {
            activo.setSelected(true);
        }
        if (Integer.parseInt(moduloConsultar.getEstado_modulo())==0) {
            inactivo.setSelected(true);
        }
        }else{
             JOptionPane.showMessageDialog(null, "Los codigos son solamente números, no incluyen ninguna letra o el campo esta vacio");
            //Si el campo esta vacio o no inserta números muestra un mensaje de error
        }
    }//GEN-LAST:event_BtnBusActionPerformed

    private void BtnIngActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngActionPerformed
        if (Mantenimiento_Modulos.isNumeric(txt_Codigo_Modulo.getText())&& txt_Codigo_Modulo.getText().length()!=0 
            && txt_Nombre_Modulo.getText().length() != 0 && txt_Descripcion_Modulo.getText().length() != 0 && limpio.isSelected()==false) {
                ModulosDAO modulosDAO = new ModulosDAO();
                Modulos moduloInsertar = new Modulos();
                moduloInsertar.setCodigo_modulo(Integer.parseInt(txt_Codigo_Modulo.getText()));
                moduloInsertar.setNombre_modulo(txt_Nombre_Modulo.getText());
                moduloInsertar.setDescripcion_modulo(txt_Descripcion_Modulo.getText());
        if (activo.isSelected()) {
                moduloInsertar.setEstado_modulo("1");
        }
        if (inactivo.isSelected()) {
                moduloInsertar.setEstado_modulo("0");
        }
                modulosDAO.insert(moduloInsertar);
                JOptionPane.showMessageDialog(null, "Modulo registrado correctamente");
                limpiar();
                actualizartabla();
                GuardarEnBitacora("Insertar",codigoAplicacion, Login.usuarioSesion);
        }else{
                JOptionPane.showMessageDialog(null, "existe campos vacios y/o el codigo no debe de llevar números");
                //Si el campo esta vacio o no inserta números muestra un mensaje de error
        }
    }//GEN-LAST:event_BtnIngActionPerformed

    private void BtnModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModActionPerformed
        if (Mantenimiento_Modulos.isNumeric(txt_Codigo_Modulo.getText())&& txt_Codigo_Modulo.getText().length()!=0 
            && txt_Nombre_Modulo.getText().length() != 0 && txt_Descripcion_Modulo.getText().length() != 0 && limpio.isSelected()==false) {
             ModulosDAO modulosDAO = new ModulosDAO();
                Modulos moduloActualizar = new Modulos();
                moduloActualizar.setCodigo_modulo(Integer.parseInt(txt_Codigo_Modulo.getText()));

                moduloActualizar.setNombre_modulo(txt_Nombre_Modulo.getText());
                moduloActualizar.setDescripcion_modulo(txt_Descripcion_Modulo.getText());
        if (activo.isSelected()) {
                moduloActualizar.setEstado_modulo("1");
        }
        if (inactivo.isSelected()) {
                moduloActualizar.setEstado_modulo("0");
        }
                modulosDAO.update(moduloActualizar);
                JOptionPane.showMessageDialog(null, "Modulo actualizado correctamente");
                limpiar();
                actualizartabla();
                GuardarEnBitacora("Modificacion",codigoAplicacion,  Login.usuarioSesion);
        }else{
            JOptionPane.showMessageDialog(null, "existe campos vacios y/o el codigo no debe de llevar números");
                //Si el campo esta vacio o no inserta números muestra un mensaje de error
        }
    }//GEN-LAST:event_BtnModActionPerformed

    private void BtnElimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnElimActionPerformed
        if (Mantenimiento_Modulos.isNumeric(txt_Codigo_Modulo.getText())&& txt_Codigo_Modulo.getText().length()!=0 
            && txt_Nombre_Modulo.getText().length() != 0 && txt_Descripcion_Modulo.getText().length() != 0 && limpio.isSelected()==false) {
            ModulosDAO modulosDAO = new ModulosDAO();
            Modulos moduloEliminar = new Modulos();
            moduloEliminar.setCodigo_modulo(Integer.parseInt(txt_Codigo_Modulo.getText()));
            modulosDAO.delete(moduloEliminar);   
            JOptionPane.showMessageDialog(null, "Modulo eliminado correctamente");
            GuardarEnBitacora("Eliminacion",codigoAplicacion,  Login.usuarioSesion);
        }else{
            JOptionPane.showMessageDialog(null, "existe campos vacios y/o el codigo no debe de llevar números");
                //Si el campo esta vacio o no inserta números muestra un mensaje de error
        }
            limpiar();
            actualizartabla();
    }//GEN-LAST:event_BtnElimActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
    limpiar();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
try {
            if ((new File("src\\main\\java\\seguridad\\ayuda\\AyudaMantenimientoModulos.chm")).exists()) {
                Process p = Runtime
                        .getRuntime()
                        .exec("rundll32 url.dll,FileProtocolHandler src\\main\\java\\seguridad\\ayuda\\AyudaMantenimientoModulos.chm");
                p.waitFor();
            } else {
                JOptionPane.showMessageDialog(null, "La ayuda no Fue encontrada");
            }
            //System.out.println("Correcto");
        } catch (Exception ex) {
            ex.printStackTrace();
        }    
    }//GEN-LAST:event_jButton2ActionPerformed
                                       

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBus;
    private javax.swing.JButton BtnElim;
    private javax.swing.JButton BtnIng;
    private javax.swing.JButton BtnMod;
    private javax.swing.JPanel CajaInformacion;
    private javax.swing.ButtonGroup ESTADO;
    private javax.swing.JRadioButton activo;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JRadioButton inactivo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton limpio;
    private javax.swing.JTable tabla1;
    private javax.swing.JTextField txt_Codigo_Modulo;
    private javax.swing.JTextArea txt_Descripcion_Modulo;
    private javax.swing.JTextField txt_Nombre_Modulo;
    // End of variables declaration//GEN-END:variables

}
